### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by xuqingfeng** [aliyun/terraform-provider-alicloud#1670]
### Terraform Version

Terraform v0.12.9
+ provider.alicloud v1.55.4

### Affected Resource(s)

- alicloud_security_group_rule

### Terraform Configuration Files

```hcl
resource "alicloud_security_group_rule" "allow_tcp_22" {
  type              = "ingress"
  ip_protocol       = "tcp"
  nic_type          = "intranet"
  policy            = "accept"
  port_range        = "22/22"
  security_group_id = alicloud_security_group.default.id
  cidr_ip           = "1.2.3.4/32"
}
```

### Expected Behavior

`terraform apply` succeed without error.

### Actual Behavior

```
alicloud_security_group_rule.allow_tcp_22: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to alicloud_security_group_rule.allow_tcp_22,
provider "alicloud" produced an unexpected new value for was present, but now
absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

But rule got added to alicloud even though `terraform apply` throw this error.

**Comment by zql-tqy** [comment]
Hi, I am sorry for late reply. I didn't repeat your question, you can pull the latest provider code and have a try. If you have any questions please contact us.
