### ISSUE TITLE
alicloud_slb_listener always try to update description value

### ISSUE THREAD

**Issue by yongzhang** [aliyun/terraform-provider-alicloud#2152]
Hi, 

I have no `description` defined in resource `alicloud_slb_listener`, looks like terraform will auto generate one with `"protocol" + "port"`, so every time I run `terraform apply` it will update value of `description` to `null`.

```
  # alicloud_slb_listener.consul_client will be updated in-place
  ~ resource "alicloud_slb_listener" "consul_client" {
        acl_status                   = "off"
        backend_port                 = 8500
        bandwidth                    = -1
        delete_protection_validation = false
      - description                  = "http_8500" -> null
        frontend_port                = 8500
        gzip                         = true
```

**Comment by zql-tqy** [comment]
Hi, I am sorry for late reply. I didn't repeat your question, you can pull the latest provider code and have a try.
