### ISSUE TITLE
[FEATURE REQUEST] PolarDb - Support attaching Security Group & Create custom endpoint to polardb cluster

### ISSUE THREAD

**Issue by yokzy88** [aliyun/terraform-provider-alicloud#2263]
1. Need to support attaching Security Group to polardb cluster
2. Need to support creating custom endpoint to polardb cluster

### Terraform Version
Terraform v0.12.17
+ provider.alicloud v1.73.0

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_polardb_cluster

### Expected Behavior
Should support attaching security group to polardb
Should support creating custom endpoint to polardb

### Actual Behavior
Currently attaching security group is unsupported
Currently creating custom endpoint is unsupported

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
1. Attach security group [API Reference](https://www.alibabacloud.com/help/doc-detail/98191.htm?spm=a2c63.p38356.b99.521.4a3f748ebjMjzK)
Use **WhitelistType** attribute = **SecurityGroup**, and use **SecurityGroupIds** attribute to set the security group
2. Create custom endpoint [API Reference](https://www.alibabacloud.com/help/doc-detail/116576.htm?spm=a2c63.p38356.b99.533.238c25d40fFD8u)

**Comment by xiaozhu36** [comment]
Hi @yokzy88 This feature has been supported in the version 1.128.0 and please refer to https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/polardb_cluster#security_group_ids.
