### ISSUE TITLE
Feature request: Let alicloud_cs_managed_kubernetes return worker role name

### ISSUE THREAD

**Issue by mlafeldt** [aliyun/terraform-provider-alicloud#2326]
At the moment, the only way to extend the permissions of the worker nodes of a K8s cluster is doing something like this:

```hcl
data "alicloud_ram_roles" "k8s_worker" {
  name_regex = "KubernetesWorkerRole-*"
}

resource "alicloud_ram_role_policy_attachment" "cr_readonly" {
  count       = length(data.alicloud_ram_roles.k8s_worker.roles)
  policy_name = "AliyunContainerRegistryReadOnlyAccess"
  policy_type = "System"
  role_name   = data.alicloud_ram_roles.k8s_worker.roles[count.index].name
}
```

However, it would be a lot simpler if `alicloud_cs_managed_kubernetes` would provide the name of the created worker role directly.

(Besides, the above workaround won't work if there's more than one cluster.)

**Comment by ringtail** [comment]
Pls label the issue and assign to me. @xiaozhu36

**Comment by mlafeldt** [comment]
This issue actually blocks destroying or recreating a K8s cluster via Terraform without manual intervention.

Terraform will fail with this non-descriptive error:

```
...
alicloud_cs_managed_kubernetes.k8s: Still destroying... [id=c973712a80c78492984e7d322946361f1, 4m50s elapsed]
alicloud_cs_managed_kubernetes.k8s: Still destroying... [id=c973712a80c78492984e7d322946361f1, 5m0s elapsed]

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_kubernetes.go:974: Resource id：c973712a80c78492984e7d322946361f1 :
unexpected state 'delete_failed', wanted target ''. last error: %!s(<nil>)
```

In the cluster events, we can see the reason:

```
Resource DELETE failed: ReleaseResourceException: resources.KubernetesWorkerRole: code: ReleaseInstanceError, message: Release resource "The role KubernetesWorkerRole-ec9d0c60-da3e-4a54-82ab-2acceb9554c8 can not been attached to any policy while deleting the role." failed.:
```

Our current workaround: Detach all policies from the affected `KubernetesWorkerRole-x` role via the RAM console, then delete the cluster via the console, then run Terraform again.

If `alicloud_cs_managed_kubernetes` would return the worker role directly, which we can then use instead of `data` source, Terraform would automatically destroy resources in the correct order.

**Comment by ringtail** [comment]
@wangyuelucky Pls take a look about this issue.

**Comment by demonwy** [comment]
hi @mlafeldt  sorry, we can't get the RamRole name yet, because it is created dynamically. 
I think the key point is who create the policy and attached to RamRole outside of cluster.

From  lifecycle management perspective, the creator is responsible for deletion.

**Comment by demonwy** [comment]
"The role KubernetesWorkerRole-ec9d0c60-da3e-4a54-82ab-2acceb9554c8 can not been attached to any policy while deleting the role."

The policy  is not created by container service. It must be created outside manually.

**Comment by mlafeldt** [comment]
Those are two different things.

The RAM role `KubernetesWorkerRole-x` always does get created when creating a new cluster (just try it out). In one of our accounts, we have three clusters and three `KubernetesWorkerRole-x` roles and we set up none of those.

The error in question happens when attaching _additional_ policies to that role and then deleting the cluster. That's what I described [above](https://github.com/terraform-providers/terraform-provider-alicloud/issues/2326#issuecomment-610959291).

Unfortunately, that is currently the only way to extend the permissions of worker nodes as it's neither possible to pass a custom role to `alicloud_cs_managed_kubernetes` nor to get the created role from it.

**Comment by yagrxu** [comment]
@mlafeldt  @demonwy  If I understand the conversation correctly. The main question is if we can automate the attaching policy automatically after the role is created and remove it before trying to remove the cluster.
KubernetesWorkerRole-x can be formated as KubernetesWorkerRole-{ID} and attach policy on it in terraform. so it will be detached before deleting the cluster in terraform.
The current issue is ID is not exported yet.
If it is possible, please kindly consider if the ID can be exported

**Comment by shakerky-awx** [comment]
I think either way would solve the issue:
1. Return the role ID so we can add policies to it (or make the role id reflect the cluster name somehow)
2. Allow custom roles to be passed and assigned to the worker nodes.

Currently the 'solution' is doing it all by hand or only having one cluster per account is unacceptable.

**Comment by liuyangc3** [comment]
@mlafeldt  You can get the role in this way, hopes example below helps you.
```hcl
# get k8s worker 
data "alicloud_instances" "worker" {
  ids   = alicloud_cs_managed_kubernetes.k8s.worker_nodes.*.id
}
# get k8s worker role id
data "alicloud_ram_roles" "this" {
  name_regex  = data.alicloud_instances.worker.instances[0].ram_role_name
  policy_type = "Custom"
}
```

**Comment by ringtail** [comment]
> here is how I does in my module
> 
> ```terraform
> # get k8s worker 
> data "alicloud_instances" "worker" {
>   ids   = alicloud_cs_managed_kubernetes.k8s.worker_nodes.*.id
> }
> # get k8s worker role id
> data "alicloud_ram_roles" "role" {
>   name_regex  = data.alicloud_instances.worker.instances[0].ram_role_name
>   policy_type = "Custom"
> }
> ```
> 
> @ringtail It will be great if adding some DescribeInstanceRamRole code after cluster created, and put a var like `worker_ram_role_id` in Argument Reference.

cc @demonwy

**Comment by demonwy** [comment]
> here is how I does in my module
> 
> ```terraform
> # get k8s worker 
> data "alicloud_instances" "worker" {
>   ids   = alicloud_cs_managed_kubernetes.k8s.worker_nodes.*.id
> }
> # get k8s worker role id
> data "alicloud_ram_roles" "role" {
>   name_regex  = data.alicloud_instances.worker.instances[0].ram_role_name
>   policy_type = "Custom"
> }
> ```
> 
> @ringtail It will be great if adding some DescribeInstanceRamRole code after cluster created, and put a var like `worker_ram_role_id` in Argument Reference.

thanks @liuyangc3 , we will add a property like `worker_ram_role_id` the next release

**Comment by mlafeldt** [comment]
> here is how I does in my module
> 
> ```terraform
> # get k8s worker 
> data "alicloud_instances" "worker" {
>   ids   = alicloud_cs_managed_kubernetes.k8s.worker_nodes.*.id
> }
> # get k8s worker role id
> data "alicloud_ram_roles" "role" {
>   name_regex  = data.alicloud_instances.worker.instances[0].ram_role_name
>   policy_type = "Custom"
> }
> ```

Thank you! That's actually a good workaround. Added it to my code like this:

```
data "alicloud_instances" "worker" {
  ids = [alicloud_cs_managed_kubernetes.k8s.worker_nodes[0].id]
}

locals {
  worker_ram_role = data.alicloud_instances.worker.instances[0].ram_role_name
}
```
