### ISSUE TITLE
data alicloud_ram_users no longer working

### ISSUE THREAD

**Issue by JanWaller** [aliyun/terraform-provider-alicloud#2329]
Since 1.76 a simple query like 
data "alicloud_ram_users" "users_devops" {
  group_name = "DevOps"
}
return with an error of:

Error: [ERROR] terraform-provider-alicloud/alicloud/data_source_alicloud_ram_users.go:196:
wrong interface convince

  on ../../../../modules/kubernetes-config/main.tf line 100, in data "alicloud_ram_users" "users_devops":
 100: data "alicloud_ram_users" "users_devops" {

In earlier versions of the provider it works fine.

**Comment by chushenmeshile** [comment]
@JanWaller This problem has been solved, please use the latest version of provider 1.100.0
