### ISSUE TITLE
[Bug] alicloud_cs_managed_kubernetes  sls_project_name in logtail-ds in addons

### ISSUE THREAD

**Issue by liuyangc3** [aliyun/terraform-provider-alicloud#2394]
### Terraform Version
```shell
Terraform v0.12.24
+ provider.alicloud v1.80.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_cs_managed_kubernetes

### Terraform Configuration Files

```hcl
# create a sls project first
resource "alicloud_log_project" "this" {
  name        = "test"
}
# set custom sls project in addons  
variables "addons" {  
  default = [{
    "name"     = "logtail-ds",
    "config"   = "{\"IngressDashboardEnabled\":\"true\",  \"sls_project_name\": \"test\"}",
  )]
}
```

### Actual Behavior
1. cluster still create a sls project in format `k8s-log-<cluster id>`.
2. and configmap `alibaba-log-configuration` still use `k8s-log-<cluster id>` as sls project.
```
kubectl get configmaps alibaba-log-configuration -n kube-system -o yaml |grep log-project
  log-project: k8s-log-xxxxx
```

### Expected Behavior
support set custom  sls project in addons.

**Comment by chushenmeshile** [comment]
@liuyangc3 I think this feature is already implemented, and you can try it out with the latest provider 1.100.0
