### ISSUE TITLE
Import WAF failed for ap-southeast-3

### ISSUE THREAD

**Issue by linuschew** [aliyun/terraform-provider-alicloud#2560]
### Terraform Version

Terraform v0.12.24
+ provider.alicloud v1.86.0

### Affected Resource(s)
Please list the resources as a list, for example:
- Alicloud_waf_domain

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "alicloud_waf_domain" "this" {
}

### Debug Output
https://gist.github.com/linuschew/12b1604faf79cc744e3acd15b9895edd

### Expected Behavior
Import successful of WAF Domain

### Actual Behavior
Failed to connect to host, retried 6 times.
dial tcp: lookup waf-openapi.ap-southeast-3.aliyuncs.com on 192.168.0.1:53: no such host

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import alicloud_waf_domain.this wafserver:waf domain'

**Comment by liuri1205** [comment]
The problem has been fixed, test provider version v1.88.0

**Comment by liuri1205** [comment]
The problem has been fixed, test version v1.88.0

**Comment by liuri1205** [comment]
The problem has been fixed, test provider version 1.88.0

**Comment by liuri1205** [comment]
The problem has been fixed, test provider version 1.89.0.
