### ISSUE TITLE
There is no attribute 'Category' in alicloud_db_instance.

### ISSUE THREAD

**Issue by YuanQY** [aliyun/terraform-provider-alicloud#2582]
### Terraform Version
 Terraform v0.12.26
+ provider.alicloud v1.86.0

### Affected Resource(s)
- alicloud_db_instance

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Provider should support 'Category' in resource 'alicloud_db_instance'. Otherwise, we can't  create cluster (One mast and one slave or one Master with two Slave) in RDS. Please refer to document about 'CreateDBInstance' at 'https://help.aliyun.com/document_detail/26228.html?spm=a2c4g.11174283.6.1583.47735b830gq1H7#h2-url-4'

### Actual Behavior
There is no atribute 'Category' in alicloud_db_instance. 

### Steps to Reproduce
N/A

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by yannrouillard** [comment]
@yanc0 Are you sure you need the `Category` field to be able to create HighAvailability instance ?
My understand was that it's the instance type you select that define if you will have a HighAvailability or Standard instance.

In my case, I was able to deploy a HighAvailability instance without needing to add this `Category` field.

**Comment by yanc0** [comment]
@yannrouillard Hi ! Wrong mention I think ;)

**Comment by yannrouillard** [comment]
Indeed I wanted to ping @YuanQY :)

**Comment by molog** [comment]
The Category field is required according to Aliyun's reply: 

> DBInstanceClass=mssql.x4.xlarge.s1，这个是基础版的规格 API请求中需要指定Category参数的取值为Basic\

Which is saying for Basic Category instanceClass, this field is required.

We met this problem when creating db_instance_class=mssql.x4.xlarge.s1. The error message was:

> Error: [31m[ERROR][0m terraform-provider-alicloud/alicloud/resource_alicloud_db_instance.go:525: Resource  CreateDBInstance Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDKError:
   StatusCode: 404
   Code: InvalidDBInstanceClass.NotFound
   Message: code: 404, The specified instance class is not found. request id: XXXXXXXX-XXX-XXXX-XXXX-XXXXXXXXXXXX
   Data: {"Code":"InvalidDBInstanceClass.NotFound","HostId":"rds.aliyuncs.com","Message":"The specified instance class is not found.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidDBInstanceClass.NotFound\u0026product=Rds","RequestId":"XXXXXXXX-XXX-XXXX-XXXX-XXXXXXXXXXXX"}
