### ISSUE TITLE
Missing attributes on alicloud_api_gateway_api: http_vpc_service_config & mock_service_config 

### ISSUE THREAD

**Issue by yokzy88** [aliyun/terraform-provider-alicloud#2586]
Hi there,

There are some attributes still missing on alicloud_api_gateway_api
1. http_vpc_service
   - protocol (HTTPS)
2. mock_service_config 
   - mock_status_code
   - mock headers

### Terraform Version
Terraform v0.12.24
+ provider.alicloud v1.82.0

### Affected Resource(s)
- alicloud_api_gateway_api

### Expected Behavior
The attributes is not supported yet

### Actual Behavior
The attributes should be supported

### References
For http-vpc protocol: [alibabacloud-sdk-go](https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/cloudapi/struct_service_config.go#L28)
For mock_status code: [alibabacloud-sdk-go](https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/cloudapi/struct_service_config.go#L32)
For mock_headers: [alibabacloud-sdk-go](https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/cloudapi/struct_service_config.go#L35)

**Comment by chushenmeshile** [comment]
@yokzy88 This problem has been solved.
