### ISSUE TITLE
Resource alicloud_cms_sitemonitor not supported anymore 

### ISSUE THREAD

**Issue by fabien-duolingo** [aliyun/terraform-provider-alicloud#2612]
### Terraform Version
```
Terraform v0.12.28
+ provider.alicloud v1.88.0
```

### Affected Resource(s)
- [alicloud_cms_sitemonitor](https://www.terraform.io/docs/providers/alicloud/r/cms_sitemonitor.html)

### Terraform Configuration Files
```hcl
resource "alicloud_cms_sitemonitor" "basic" {
      address = "http://www.alibabacloud.com"
      task_name = "tf-testAccCmsSiteMonitor_basic"
      task_type = "HTTP"
      interval = 5
      isp_cities {
        city = "546"
        isp = "465"
      }
}
```
Note that there is also an error on the example usage on the documentation (extra closing curly brace) : https://www.terraform.io/docs/providers/alicloud/r/cms_sitemonitor.html

### Debug Output
Console output of `terraform plan`
```
Error: Invalid resource type

  on cms.tf line 13, in resource "alicloud_cms_sitemonitor" "basic":
  13: resource "alicloud_cms_sitemonitor" "basic" {

The provider provider.alicloud does not support resource type
"alicloud_cms_sitemonitor".
```

### Expected Behavior
alicloud_cms_sitemonitor is supposed to be a valid resource

### Actual Behavior
Got the error above

### Steps to Reproduce
1. `terraform plan`

**Comment by liuri1205** [comment]
The problem has been fixed in version 1.89.0 , thanks for your feedback.
