### ISSUE TITLE
Serverless Kubernetes Cluster: missing and outdated paramaters

### ISSUE THREAD

**Issue by arafato** [aliyun/terraform-provider-alicloud#2631]
Hi there,

the Serverless Kubernetes Cluster resource provider https://github.com/terraform-providers/terraform-provider-alicloud/blob/master/alicloud/resource_alicloud_cs_serverless_kubernetes.go

has two flaws:
- the parameter `vswitch_id` should accept an array of multiple vswitch ids and also be renamed to `vswitch_ids` accordingly. The current OpenAPI supports more than one vswitch to account for Multi-AZ setup.
- the parameter `addons` is missing and needs to be added to be able to configure LogService automatically, for example.

Thanks!

**Comment by chushenmeshile** [comment]
@arafato This problem has been solved
