### ISSUE TITLE
Remove github.com/hashicorp/terraform import

### ISSUE THREAD

**Issue by kmoe** [aliyun/terraform-provider-alicloud#2674]
This provider imports both `github.com/hashicorp/terraform` (Terraform Core) and `github.com/hashicorp/terraform-plugin-sdk` (Terraform Plugin SDK):
https://github.com/terraform-providers/terraform-provider-alicloud/blob/d6cddb34a1dc882e0bba0a86098c637e8d57f354/go.mod#L23

These imports are incompatible, and the Terraform Core import should be removed. The Terraform Core import is likely adding significantly to this provider's compiled binary size.

References to Terraform Core, e.g. https://github.com/terraform-providers/terraform-provider-alicloud/blob/2b4ba99543af0eeabc0a056a679d1c0cdc165550/alicloud/import_alicloud_cen_bandwidth_limit_test.go#L6, can be replaced with the corresponding packages in the Terraform Plugin SDK.

See the documentation for more information about migrating to the Terraform Plugin SDK:
https://www.terraform.io/docs/extend/plugin-sdk.html

Please contact the Terraform team if you need more help.

**Comment by xiaozhu36** [comment]
Fixed by #2722
