### ISSUE TITLE
when I add cidr_IP 172.16.0.1/32(I already have 2 cidr_ip ,want to add one more),after I applied terraform,cirdir_ip never added to my server

### ISSUE THREAD

**Issue by clouda3** [aliyun/terraform-provider-alicloud#2755]
resource "alicloud_security_group_rule" "allow_3000" {
type = "ingress"
ip_protocol = "tcp"
nic_type = var.nic_type
policy = "accept"
port_range = "3000/3000"
priority = 1
security_group_id = alicloud_security_group.group.id
#TO BE MODIFIED
cidr_ip = "172.16.0.20/32,172.16.0.30/32,172.16.0.1/32"
}

[1m�[31mError: �[0m�[0m�[1mProvider produced inconsistent result after apply�[0m

�[0mWhen applying changes to alicloud_security_group_rule.allow_3100, provider
"registry.terraform.io/hashicorp/alicloud" produced an unexpected new value:
Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by chushenmeshile** [comment]
@clouda3  Your `cidr_ip` IP value description is incorrect. Only one IP value can be filled in and cannot be separated by commas.Such as : cidr_ip = "172.16.0.20/32"

**Comment by clouda3** [comment]
> @clouda3 Your `cidr_ip` IP value description is incorrect. Only one IP value can be filled in and cannot be separated by commas.Such as : cidr_ip = "172.16.0.20/32"

you are right,
I checked the document:
cidr_ip - (Optional, ForceNew) The target IP address range. The default value is 0.0.0.0/0 (which means no restriction will be applied). Other supported formats include 10.159.6.18/12. Only IPv4 is supported.
I can not find any examples can support multiple cidr_ip
