### ISSUE TITLE
Add Resource Enterprise Resource Sharing 

### ISSUE THREAD

**Issue by supertom25** [aliyun/terraform-provider-alicloud#2765]
Hi there,

We are using the Enterprise Resource management funcation and sharing resources cross the account. But this feature is not yet availale in terraform yet. 

The function of Resource Share which is not released officially, but document about "Resource Directory"
https://www.alibabacloud.com/help/doc-detail/132172.htm?spm=a2c63.p38356.b99.2.39603510Vk65hy

So we would like to add the option to configure the sharing the resource with Terraform please?

Thanks,
Tom

**Comment by chushenmeshile** [comment]
@supertom25 Terraform already supports the resource manager operation. You can refer to the following link[https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/resource_manager_account](url)

**Comment by supertom25** [comment]
It just supporting the Resource manager operations but not yet the "Sharing resources"
like i need to share a vswitches to other account. today we can only do it from Console manually.

thanks,

**Comment by chushenmeshile** [comment]
@supertom25 You can use `alicloud_resource_manager_handshake` resource, this is doc link . [https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/resource_manager_handshake](url)

**Comment by supertom25** [comment]
Hello,

Sorry but that not the function i am looking for. I am looking for the feature for resources "Sharing" not invite account into RD.
i have check the Terraform io provider which nothing could help for the moment,
thanks,

Tom

**Comment by chushenmeshile** [comment]
@supertom25 Can you tell me how to use this function? I don't even know how to operate in the console. Thank you！

**Comment by supertom25** [comment]
Hello,

As what i knew it is not yet an official release feature for Resource management in International site. (but should be released in Aliyun).

Please read below 2 screen shot for this functions,
thanks,

![image](https://user-images.githubusercontent.com/63228338/94635738-efedf000-0305-11eb-9979-4ec83be5caaa.png)
![image](https://user-images.githubusercontent.com/63228338/94635744-f41a0d80-0305-11eb-8c30-9f86ae91454e.png)

**Comment by chushenmeshile** [comment]
@supertom25 Thank you, at present, this resource is not supported. We will add it later

**Comment by supertom25** [comment]
Hello, the resources is presented in v1.111.0. Issue is good to close, 
thanks,
