### ISSUE TITLE
alicloud_slb_acl : I'm not able to add IP address on the Entry Its only work with CDR block

### ISSUE THREAD

**Issue by mhamaydeh** [aliyun/terraform-provider-alicloud#2778]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.12.29
+ provider.alicloud v1.94.0

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_slb_acl

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
resource "alicloud_slb_acl" "default" {
  name       = "test_acl"
  ip_version = "ipv4"
  entry_list {
    entry   = "10.10.10.0"
    comment = "first"
  }
  entry_list {
    entry   = "168.10.10.0"
    comment = "second"
  }
}
### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_slb_acl.go:159:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_slb.go:460: Resource acl-uf6pt88x6bkoaukbhmisu AddAccessControlListEntry Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InvalidEntry
Recommend: 
RequestId: BD14F3CA-B678-43BD-A353-DE09855FA29B
Message: The entry format is invalid

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
should be able to add IP not only CDR block , with entry CDR block it works fine 
### Actual Behavior
What actually happened?
I'm not able to add ACL entry for IP address . 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by chushenmeshile** [comment]
@mhamaydeh  Your parameters do not meet the requirements, you should do so. 
`resource "alicloud_slb_acl" "default" {
  name = "test_acl"
  ip_version = "ipv4"
  entry_list {
    entry = "10.10.10.0/24"
    comment = "first"
  }
  entry_list {
    entry = "168.10.10.0/24"
    comment = "second"
  }
}`

**Comment by mhamaydeh** [comment]
thank you @chushenmeshile
