### ISSUE TITLE
alicloud_network_acl_attachment "inconsistent result after apply"

### ISSUE THREAD

**Issue by elsnepal** [aliyun/terraform-provider-alicloud#2905]
`alicloud_network_acl_attachment` doesnot support binding more than one vswitch; This is however working with UI or alicloud api.

Error: Provider produced inconsistent result after apply

### Terraform Version
Terraform v0.12.29
+ provider.alicloud v1.100.0

### Affected Resource(s)

- alicloud_network_acl_attachment

### Terraform Configuration Files
```hcl
resource "alicloud_network_acl" "default" {
  vpc_id      = var.vpc_id
  name        = var.nacl_name
  description = var.nacl_description
}

resource "alicloud_network_acl_attachment" "default1" {
  network_acl_id = alicloud_network_acl.default.id
  resources {
      resource_id = "vsw-xxxxxxxxxxxxxxxxx"
      resource_type = "VSwitch"
  }
}

resource "alicloud_network_acl_attachment" "default" {
  network_acl_id = alicloud_network_acl.default.id
  resources {
      resource_id = "vsw-xxxxxxxxxxxxxxxxxyyyy"
      resource_type = "VSwitch"
  }
}
```

### Panic Output
```
module.nacl.alicloud_network_acl_attachment.default: Creating...
module.nacl.alicloud_network_acl_attachment.default1: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to module.nacl.alicloud_network_acl_attachment.default1,
provider "registry.terraform.io/-/alicloud" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent result after apply

When applying changes to module.nacl.alicloud_network_acl_attachment.default,
provider "registry.terraform.io/-/alicloud" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
Should exit successfully and store values in state file so at the next run it does not try to create again.

### Actual Behavior
Creates resource but fails with inconsistent results message.

### Steps to Reproduce

1. unbind resource
2. `terraform apply`

**Comment by chushenmeshile** [comment]
@elsnepal There is something wrong with your template. It should be written like this.
`resource "alicloud_network_acl_attachment" "default1" {
  network_acl_id = alicloud_network_acl.default.id
  resources {
      resource_id = "vsw-xxxxxxxxxxxxxxxxx"
      resource_type = "VSwitch"
  }
  resources {
      resource_id = "vsw-xxxxxxxxxxxxxxxxxyyyy"
      resource_type = "VSwitch"
  }
}`

**Comment by elsnepal** [comment]
Hey @chushenmeshile, you are right, it seems it does not like to create individually with the count. 

Also i had tested that way; it turns out i had `Vswitch` in that case; which means I was seeing a slightly different issues.

```
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_network_acl_attachment.go:168: Resource nacl-bp1asv1nv9dhxe4cppred:terraform-20201016092602850100000003 AssociateNetworkAcl Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InternalError
Recommend: https://error-center.aliyun.com/status/search?Keyword=InternalError&source=PopGw
RequestId: 255A4DC1-687B-42A7-9EB8-544F76D3880C
Message: The request processing has failed due to some unknown error.

  on .terraform/modules/vpc.nacl/nacl.tf line 7, in resource "alicloud_network_acl_attachment" "default":
   7: resource "alicloud_network_acl_attachment" "default" {
```

Anyway, thank you for pointing this out. And I will go ahead and close this.
