### ISSUE TITLE
alicloud_oss_bucket documentation page under registre.terraform.io markup broken

### ISSUE THREAD

**Issue by wolfwolker** [aliyun/terraform-provider-alicloud#2914]
The documentation page for alicloud_oss_bucket resource has broken markup, probably due to some EOF mark or something like that. The mess begins after `set bucket policy`. See https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/oss_bucket

### Terraform Version

Latest.

### Affected Resource(s)

- alicloud_oss_bucket
- documentation

**Comment by chushenmeshile** [comment]
@wolfwolker I don't quite understand what mistakes you want to describe. What's wrong with this resource

**Comment by wolfwolker** [comment]
it's not the resource itself but the documentation page. I'm sorry if this is not the proper place to notify that kind of bug.

In this screenshoot you can see that after set bucket policy section the styles are different/broken
![image](https://user-images.githubusercontent.com/1926137/96221154-51f75800-0f8a-11eb-9d4b-da264a9e62db.png)

**Comment by chushenmeshile** [comment]
@wolfwolker This problem has been solved. [https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/oss_bucket](url)
