### ISSUE TITLE
alicloud_db_instance vswitch_id error

### ISSUE THREAD

**Issue by lohasfeng123** [aliyun/terraform-provider-alicloud#2948]
My script:
resource "alicloud_db_instance" "instance" {
  engine           = "MySQL"
  engine_version   = "5.7"
  instance_type    = "rds.mysql.t1.small"
  instance_name    = "wp_db"
  instance_storage = "10"
  vswitch_id       = [alicloud_vswitch.vsw1_bj_c.id, alicloud_vswitch.vsw2_bj_e.id] 
  security_ips     = ["172.16.0.0/21,172.18.0.0/21"]
}

There is something wrong with the arguments  of "vswitch_id"        
      + sql_collector_config_value = 30
      + sql_collector_status       = (known after apply)
      + ssl_action                 = (known after apply)
      + ssl_status                 = (known after apply)
      + vswitch_id                 = "vsw-2zehvyiyzz2t5vhad2nvl,vsw-2zesqss3s030kvbss4du1"
      + zone_id                    = (known after apply)

      + parameters {
          + name  = (known after apply)
          + value = (known after apply)
        }
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

alicloud_db_instance.instance4: Creating...

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_instance.go:265: Resource  CreateDBInstance Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InvalidVpcId.NotSupported
Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidVpcId.NotSupported&source=PopGw
RequestId: 43559C3D-D01F-4E59-8174-193E6C5D9ACF
Message: The specified vpcId or vSwitchId is not supported.

  on ss.tf line 210, in resource "alicloud_db_instance" "instance4":
 210: resource "alicloud_db_instance" "instance4" {

**Comment by yannrouillard** [comment]
Hi @lohasfeng123,

You should specify vswitchId as a comma separated list of vswitch id, not as an array.

You should have more something like:

```
 vswitch_id = join(", ", [alicloud_vswitch.vsw1_bj_c.id, alicloud_vswitch.vsw2_bj_e.id])
```

**Comment by lohasfeng123** [comment]
Hi
Thank you for your help .
But,there is still some error.I tried the official demo,It has same error....
"Message: The Specified Zone not supported."

I choose the  region cn-beijing.

official demo:
variable "name" {
  default = "tf-testaccdbinstance"
}

data "alicloud_zones" "example" {
  available_resource_creation = "Rds"
}

resource "alicloud_vpc" "example" {
  name       = var.name
  cidr_block = "172.16.0.0/16"
}

resource "alicloud_vswitch" "example" {
  count             = 2
  vpc_id            = alicloud_vpc.example.id
  cidr_block        = format("172.16.%d.0/24", count.index+1)
  availability_zone = data.alicloud_zones.example.zones[count.index].id
  name              = format("vswich_%d", var.name, count.index)
}

resource "alicloud_db_instance" "example" {
  engine               = "MySQL"
  engine_version       = "5.6"
  instance_storage     = "30"
  instance_type        = "rds.mysql.t1.small"
  instance_charge_type = "Postpaid"
  instance_name        = var.name
  zone_id              = data.alicloud_zones.example.zones.0.id
  zone_id_slave_a      = data.alicloud_zones.example.zones.1.id
  vswitch_id           = join(",", alicloud_vswitch.example.*.id)
  monitoring_period    = "60"
}

**Comment by lohasfeng123** [comment]
I change the region beijing to hangzhou.
The rds created successfully,but it is classic network......
