### ISSUE TITLE
[Feature Request] RDS PostgreSQL (ApSaraDB) KMS support

### ISSUE THREAD

**Issue by ZPascal** [aliyun/terraform-provider-alicloud#3127]
I would like to use the database disk encryption functions provided by Alicloud also by means of Terraform.

**Comment by xiaozhu36** [comment]
HI @ZPascal I am sorry for the late reply. Currently, the release v1.109.0 has supported it and you can refer to docs: https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/db_instance#encryption_key . Please let me know if you have other issues.
