### ISSUE TITLE
Unexpected changes in terraform plan (Trying to recreate ECS instance).

### ISSUE THREAD

**Issue by vmugutrao** [aliyun/terraform-provider-alicloud#3135]
Hi there,

We had deployed couple of ECS instance using terraform code, while deployment we created data disk inside "alicloud_instance"
And we did not specified **performance_level** attribute and by default all data disk got deployed as PL1.

Now after couple of weeks we are seeing terraform plan is showing destroy changes, where its going to destroy ECS instance and re-provision them, 
and its showing because performance_level   value ( + performance_level    = "PL1" # forces replacement), 
though its same on GUI and terraform plan. 

I have other ECS instance where data disk is created separately and  performance_level was defined as PL1, its coming in TF plan, only data disk which is created inside ECS instance code is giving this behavior.  

### Terraform Version
Terraform v0.13.3

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_instance

### Terraform Configuration Files
```hcl
# To deploy  Node1 for devlopment
resource "alicloud_instance" "tableau-twk1-dev" {
  instance_name           = var.twk_node1_name
  host_name               = var.twk_node1_name
  instance_type           = "ecs.g6.4xlarge"
  image_id                = var.image_teamplate
  availability_zone       = "cn-shanghai-g"
  instance_charge_type    = "PrePaid"
  period_unit             = "Month"
  period                  = "3"
  renewal_status          = "AutoRenewal"
  system_disk_name        = "${var.twk_node1_name}-osdisk1"
  system_disk_description = "OS Disk for ${var.twk_node1_name}"
  system_disk_category    = "cloud_essd"
  system_disk_size        = 80
  data_disks {
    name        = "${var.twk_node1_name}-datadisk1"
    size        = 100
    category    = "cloud_essd"
    description = "Data Disk1 for ${var.twk_node1_name}"
    encrypted   = true
  }
  resource_group_id = var.resource_group
  vswitch_id        = var.vswitch1_id
  security_groups   = alicloud_security_group.sg-tableau-dev-01.*.id
  description       = "Worker Node 1"
}
```

### Debug Output
I am not confirming change as my ECS instances are in use and i don't want them to be replaced.

### Expected Behavior
It should not plan any thing as there is no change in code.

### Actual Behavior
Trying to destroy and recreate ECS instance. 

### Steps to Reproduce
1. `terraform plan`

**Comment by Shadowraze228** [comment]
Bump this, same issue

**Comment by vmugutrao** [comment]
Thanks for prompt fix :)
