### ISSUE TITLE
PolarDB - TDE Full Database Encryption

### ISSUE THREAD

**Issue by brianmori** [aliyun/terraform-provider-alicloud#3243]
PolarDB should give the possibility to encrypt the whole database

It is not efficient and error prone to encrypt single tables

**Comment by xiaozhu36** [comment]
HI @brianmori This feature has been supported in the version 1.124.1 : https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/polardb_cluster#encrypt_new_tables
You can set `tde_status = "Enabled"` and `encrypt_new_tables = "ON"` to do it.
