### ISSUE TITLE
eip-gw8i931ox9w4mo2g6r9an DescribeEipAddresses Failed!!! [SDK alibaba-cloud-sdk-go ERROR]

### ISSUE THREAD

**Issue by Thomas999999** [aliyun/terraform-provider-alicloud#3285]
Hi there,

### Terraform Version
.....
+ TERRAFORM_VERSION=0.12.30
+ wget https://releases.hashicorp.com/terraform/0.12.30/terraform_0.12.30_linux_amd64.zip
--2021-02-15 11:52:10--  https://releases.hashicorp.com/terraform/0.12.30/terraform_0.12.30_linux_amd64.zip
Resolving releases.hashicorp.com (releases.hashicorp.com)... 151.101.1.183, 151.101.65.183, 151.101.129.183, ...
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.1.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28433523 (27M) [application/zip]
Saving to: ‘terraform_0.12.30_linux_amd64.zip’

### Affected Resource(s)

alicloud_eip_association

### Terraform Configuration Files
```hcl

snip...

# Create a new EIP for jumphost
resource "alicloud_eip" "jumphost" {
  depends_on = [ "alicloud_instance.jumphost" ]
  bandwidth            = "100"
  internet_charge_type = "PayByTraffic"

  tags = {
    instance_group_01 = "${var.instance_group_01}"
    pqp_testnumber    = "${var.pqp_testnumber}"
  }
}

# bind EIP to jumphost
resource "alicloud_eip_association" "eip_jump" {
  depends_on = [ "alicloud_eip.jumphost" ]
  allocation_id = "${alicloud_eip.jumphost.id}"
  instance_id   = "${alicloud_instance.jumphost.id}"
}

snap...

```

### Expected Behavior
EIP should be created and assigned to an instance, which worked fine since month..

### Actual Behavior
Suddenly (since last week) getting error:

...

alicloud_instance.jumphost: Still creating... [10s elapsed]
alicloud_instance.jumphost: Still creating... [20s elapsed]
alicloud_instance.jumphost: Still creating... [30s elapsed]
alicloud_instance.jumphost: Still creating... [40s elapsed]
alicloud_instance.jumphost: Still creating... [50s elapsed]
alicloud_instance.jumphost: Still creating... [1m0s elapsed]
alicloud_instance.jumphost: Creation complete after 1m2s [id=i-gw81zyk6t5he6re1xm87]
alicloud_eip.jumphost: Creating...
alicloud_eip.jumphost: Creation complete after 5s [id=eip-gw8i931ox9w4mo2g6r9an]
alicloud_eip_association.eip_jump: Creating...
alicloud_eip_association.eip_jump: Still creating... [10s elapsed]
alicloud_eip_association.eip_jump: Still creating... [20s elapsed]
alicloud_eip_association.eip_jump: Still creating... [30s elapsed]
....
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_eip_association.go:122:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_vpc.go:53:
[ERROR] terraform-provider-alicloud/alicloud/service_alicloud_vpc.go:34: Resource eip-gw8i931ox9w4mo2g6r9an DescribeEipAddresses Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:

  on ali_ecs_jumphost.tf line 119, in resource "alicloud_eip_association" "eip_jump":
 119: resource "alicloud_eip_association" "eip_jump" {
.....

And the mentioned eip-gw8i931ox9w4mo2g6r9an is  available in Alibaba Console VPC/Elastic IP Addresses
overview and also the EIP is assigned to correct instance..

So why does this error occurs and terminating the tarraform script to proceed with furthjer resource creation?

**Comment by Thomas999999** [comment]
Dear Support,
any update on this, currently we cannot setup our test environments due to this.
Thanks in advance

**Comment by lorenzogherdovich** [comment]
Hello,
I was not expecting to see AccessKeyId as a  clear text string. Am I wrong? Is it correct behaviour?

**Comment by Thomas999999** [comment]
thanks, closing as solved/did not occur anymore...
