### ISSUE TITLE
terraform plan doesn't warn about invalide database name

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3300]
Hi,

the `terraform plan` command doesn't fail when the database name is invalid, if it starts with capital letters.

terraform version: 0.12.26
provider version: ~> 1.93.0
affected resource: `alicloud_db_database`

Expected result:

When trying to create a database with an invalid name (e.g. starting with a capital letter) the `terraform plan` command should fail and tell the user that the used database name is invalid.

**Comment by xiaozhu36** [comment]
HI @aschleifer I am sorry for the late reply. Currently, the alicloud_db_database does not support setting account name with a capital letter and it has been marked in the docs: https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/rds_account#account_name. If you have the requirement, I can push the requirement to the RDS product team. 
Please let me know your idea.

**Comment by aschleifer** [comment]
I don't have the requirements, but I would like to see an error when I run `terraform plan` with a malformed database name. Currently it only fails during `terraform apply` which in our workflow is too late, as the code is then already merged to master. From my understanding such validations should happen in plan.

**Comment by xiaozhu36** [comment]
@aschleifer Got it. I will add a validation for this resource and this will be supported in the next version.

**Comment by xiaozhu36** [comment]
HI. @aschleifer This issue has been fixed in the version 1.122.1 and please have a check.
