### ISSUE TITLE
terrform plan for cluster size increase ran through but cluster was not changed

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3301]
Hello,

We have a cluster configured with terraform in us-west-1 and at some point we decided to increase the cluster size from `4` to `10` nodes.

The change looked good and `terraform plan` also had no issues. So we applied it with `terraform apply` to production and the execution finished without issues. But even 30 minutes later the cluster size wasn't changed.

While investigating this deeper we found this error message in the alicloud web console from ESS:
```
    Status    Failed
    Instances After Scaling    4
    Start Time    Nov 2, 2020 6:11 PM
    End Time    Nov 2, 2020 6:12 PM
    Cause

    A user requests to execute scaling rule "asr-rj97w6do6qrpfia8qx4p", changing the Total Capacity from "4" to "10".

    Status Description    -

    Details

    Fail to create Instances into scaling group(code:"InvalidSystemDiskCategory.ValueNotSupported", msg:"The specified parameter SystemDisk.Category is not valid."). Fail to create Instances into scaling group(code:"InvalidSystemDiskCategory.ValueNotSupported", msg:"The specified parameter SystemDisk.Category is not valid.").

    Description

    Add "6" ECS instances
```

It turned out later that the instance type `ecs.g6.4xlarge` we wanted to use was not compatible to ACS, since the cluster was configured to use `cloud_ssd` but the instance type itself didn't support this.

We could fix the issue by changing the instance type.

**expected behavior:**
- `terraform plan` should fail and tell the user that this instance type is not compatible with the disk type that the cluster is configured for.

**additional information:**
terraform version: 0.12.26
provider version: ~> 1.88.0
affected resource: alicloud_cs_managed_kubernetes

Best regards

**Comment by xiaozhu36** [comment]
@aschleifer I am sorry for late reply. `terraform plan` can not tell the potential error. But, the latest version 1.120.0 adds a feature that the data source alicloud_instance_types supports filtering the instance types by system_disk_category. I think it is a workaround and you can have a check.

**Comment by aschleifer** [comment]
Thanks for this information. We will use this data provider to avoid such issues in the future.
