### ISSUE TITLE
Please provide a compatibility matrix between the provider and terraform

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3306]
Hi,

in order to plan our upgrade from an old version of this provider (1.88.0) on terraform 12 we need a matrix defining which version of this provider is compatible to which version range of terraform.

It should look something like this (example data):

Provider version | minimum supported terraform version | maxmimum supported terraform version
--- | --- | ---
1.88.0 | 0.11.0 | 0.12.28
1.93.0 | 0.12.0 | 0.13.3

We need this data to find out how we can safely update our infrastructure in multiple steps, like update TF to an intermedium version, then update the provider to a newer version and so on.

Best regards

**Comment by xiaozhu36** [comment]
HI @aschleifer I am sorry for late reply. The TF v12 and v13 can supports all of alibaba cloud provider. You can update your infra safely.

**Comment by aschleifer** [comment]
Thanks for the reply. This is already good news as it saves some work in the upgrade process. In the long run we still need this compatibility matrix for future reference.

Also what about TF 14? From the release notes it doesn't look like there are any major breaking issue sin their, so would the provider also work with that? If so we could upgrade directly to TF 14.

**Comment by xiaozhu36** [comment]
@aschleifer About TF 14, we have not made a test yet. In the April, we will do it and give an official statement.

**Comment by xiaozhu36** [comment]
HI. @aschleifer We have added the `supported versions` in the README: https://github.com/aliyun/terraform-provider-alicloud#supported-versions.
In addition, we will add a docs in the registry website while publishing the next provider version.
