### ISSUE TITLE
Invalid warning for route_table_name

### ISSUE THREAD

**Issue by jurikolo** [aliyun/terraform-provider-alicloud#3381]
I'm using aliyun/alicloud version 1.119.1. When I want to create a new route table, I get following warning:
```bash
Warning: "name": [DEPRECATED] Field 'name' has been deprecated from provider version 1.120.0. New field 'route_table_name' instead.
```

Due to my version is lower than provided in an error, I suspect warning is incorrect and shall not be displayed. There is no documentation about the field route_table_name at the moment of bug creation.

### Terraform Version
$ terraform -v
Terraform v0.14.9
+ provider registry.terraform.io/aliyun/alicloud v1.119.1
+ provider registry.terraform.io/hashicorp/alicloud v1.119.1

### Affected Resource(s)
- alicloud_route_table

### Terraform Configuration Files
N/A

### Debug Output
N/A, due to bug doesn't require execution

### Expected Behavior
No warning is returned

### Actual Behavior
Got following warning:
```bash
Warning: "name": [DEPRECATED] Field 'name' has been deprecated from provider version 1.120.0. New field 'route_table_name' instead.
```

### Steps to Reproduce
1. Checkout following repository: https://github.com/jurikolo/terraform-alicloud/tree/bug/route_table_name_warning (correct branch already provided in URL)
2. go to directory live/dev/network
3. execute `terraform apply -var-file="test.tfvars"`

### Important Factoids
You can comment out AWS S3 bucket as a backend, it doesn't affect the warning

**Comment by xiaozhu36** [comment]
Hi @jurikolo I am sorry for the late reply. I have checked it and I found it has been corrected and you can refer to: https://github.com/aliyun/terraform-provider-alicloud/blob/master/alicloud/resource_alicloud_route_table.go#L44

**Comment by jurikolo** [comment]
Great, closing the issue.
