### ISSUE TITLE
alicloud_alidns_domain invalid export parameters

### ISSUE THREAD

**Issue by jurikolo** [aliyun/terraform-provider-alicloud#3410]
### Terraform Version
```bash
$ terraform -v
Terraform v0.14.9
+ provider registry.terraform.io/aliyun/alicloud v1.120.0
+ provider registry.terraform.io/hashicorp/alicloud v1.120.0
```

### Affected Resource(s)
- alicloud_alidns_domain

### Expected Behavior
When I choose to export variable `dns_server`, terraform shall return a list of DNS servers

### Actual Behavior
I get following error:
```bash
Error: Unsupported attribute

  on ../../../modules/static-website/outputs.tf line 17, in output "dns_servers":
  17:   value       = alicloud_alidns_domain.domain.dns_server

This object has no argument, nested block, or exported attribute named
"dns_server". Did you mean "dns_servers"?
```

### Steps to Reproduce
1. Create a resource `alicloud_alidns_domain`
2. Create output variable like `alicloud_alidns_domain.domain.dns_server`
3. Execute the module

### References
According to https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/alidns_domain#dns_server, dns_server is the name of export variable, but actually it works when variable name is changed to `dns_servers`

**Comment by xiaozhu36** [comment]
Hello @jurikolo I am sorry for that there is a docs error and it should be `dns_servers`. I have corrected it by the #3434
