### ISSUE TITLE
Terraform bug in v1.121.1 for data.resource.alicloud_nat_gateways

### ISSUE THREAD

**Issue by supertom25** [aliyun/terraform-provider-alicloud#3451]
Hi, 
### Terraform Version
v0.13.5

### Affected Resource(s)
data resource "alicloud_nat_gateways"

### Terraform Configuration Files
provider "alicloud" {
    region = "cn-shanghai"
    profile = "xxxxxxx"
}

data "alicloud_nat_gateways" "this" {
  name_regex = "connectivity-nprd-vpc"
}

output "gateways" {
  value = data.alicloud_nat_gateways.this.gateways
}

### Error
Error: .gateways[0].ip_lists[0]: missing expected {

### Expected Behavior
Plan success

### Actual Behavior
Plan failed with error: Error: .gateways[0].ip_lists[0]: missing expected {

### Steps to Reproduce
1. `terraform plan`

### References
Issue happened after v1.121.0 (I tested v1.120.0 is work fine)

**Comment by xiaozhu36** [comment]
Hi @supertom25 I am sorry for this issue. This issue has been fixed by 1.121.2. Please check it.
