### ISSUE TITLE
period gets added to alicloud_eip in 1.121.1 which forces renewal

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3457]
Hello,

I stumbled over a bug in verison 1.121.1:

the `period` attribute gets added to the `alicloud_eip` resource. This triggers a `ForceNew` on the resources as defined in the [documentation](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/eip#period). This is especially bad for VPC definitions as this will force eip associations and snat entries to be replaced also.

A workaround for this is to manually edit the state and add the `period = 1` to the `alicloud_eip` resources by hand.

The bug was introduced with commit https://github.com/aliyun/terraform-provider-alicloud/commit/81ceed0f15d6b6632477a4c51188935a53bde6c6 as during this change the `strings.ToLower()` around the `d.Get("instance_charge_type")` is being removed. This results in the code only accepting "postpaid" as a valid value but the state actually has "PostPaid" in it.

**Comment by xiaozhu36** [comment]
Hi @aschleifer I am sorry for this issue. It has been fixed by the #3445  and we plan to published a new release tomorrow.

**Comment by aschleifer** [comment]
Yes, I can confirm that this is fixed by [1.121.2](https://github.com/aliyun/terraform-provider-alicloud/releases/tag/v1.121.2).
