### ISSUE TITLE
terraform init reponse two providers

### ISSUE THREAD

**Issue by yarongdeng** [aliyun/terraform-provider-alicloud#3484]
Hi there,

### Terraform Version
Terraform v0.15.0
on linux_amd64

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    alicloud = {
       source  = "registry.terraform.io/hashicorp/alicloud"
    }
  }
}

provider "alicloud" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region
}


module "vpc" {
  source   = "./moudle/vpc"
  vpc_name = "test"
}

--------------moudle-vpc--main.tf-------------
resource "alicloud_vpc" "vpc" {
  vpc_name          = var.vpc_name
  cidr_block        = var.vpc_cidr
}
```

### Debug Output
#terraform init
Initializing modules...
- vpc in moudle/vpc

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/alicloud...
- Installing hashicorp/alicloud v1.121.2...
- Installed hashicorp/alicloud v1.121.2 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Additional provider information from registry
│
│ The remote registry returned warnings for registry.terraform.io/hashicorp/alicloud:
│ - For users on Terraform 0.13 or greater, this provider has moved to aliyun/alicloud. Please update your source in required_providers.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    alicloud = {
       source  = "aliyun/alicloud"
    }
  }
}

provider "alicloud" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region
}


module "vpc" {
  source   = "./moudle/vpc"
  vpc_name = "test"
}

--------------moudle-vpc--main.tf-------------
resource "alicloud_vpc" "vpc" {
  vpc_name          = var.vpc_name
  cidr_block        = var.vpc_cidr
}
```

### Panic Output
#terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding latest version of aliyun/alicloud...
- Finding latest version of hashicorp/alicloud...
- Installing aliyun/alicloud v1.121.2...
- Installed aliyun/alicloud v1.121.2 (signed by a HashiCorp partner, key ID 6722E8222F8AD935)
- Installing hashicorp/alicloud v1.121.2...
- Installed hashicorp/alicloud v1.121.2 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Additional provider information from registry
│
│ The remote registry returned warnings for registry.terraform.io/hashicorp/alicloud:
│ - For users on Terraform 0.13 or greater, this provider has moved to aliyun/alicloud. Please update your source in required_providers.
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

#terraform paln
╷
│ Error: Invalid provider configuration
│
│ Invalid type option, support: access_key, sts, ecs_ram_role, ram_role_arn, rsa_key_pair
│
│ Provider "registry.terraform.io/hashicorp/alicloud" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.
│
╵

### Expected Behavior
First terraform init ,terraform plan
Then terraform create resources

In first terraform configfile ,we use source  = "registry.terraform.io/hashicorp/alicloud",maybe in root moudle we call child moudle vpc,and we use default source path "registry.terraform.io/hashicorp/alicloud",so we init one provider sdk,but the alicloud reponse support we use source = "aliyun/alicloud"

### Actual Behavior
In second  terraform configfile ,we use source = "aliyun/alicloud", in root moudle we call child moudle vpc,and we use source path "aliyun/alicloud",so we init two provider sdk:
- Installing aliyun/alicloud v1.121.2...
- Installing hashicorp/alicloud v1.121.2...
The hashicorp/alicloud is not configured by us,we don't know where it came from.In order to only use the root module provider ,so we don't set provider config in child moudle,but in terraform plan step it report:
╷
│ Error: Invalid provider configuration
│
│ Invalid type option, support: access_key, sts, ecs_ram_role, ram_role_arn, rsa_key_pair
│
│ Provider "registry.terraform.io/hashicorp/alicloud" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.
│
╵
If we use source = "aliyun/alicloud" (as suggested)， and don’t set the provider in the submodule,what should we do.

### Steps to Reproduce
terraform init
terraform plan

### Important Factoids
N/A

**Comment by rsun-thoughtworks** [comment]
Same here.

**Comment by rsun-thoughtworks** [comment]
@xiaozhu36 I have the same issue. And cannot get latest version of alicloud because override by hashicorp.

**Comment by rsun-thoughtworks** [comment]
@yarongdeng I have solved the issue.
You need to add 
```hcl
terraform {
  required_providers {
    alicloud = {
      source  = "aliyun/alicloud"
      version = "1.124.1"
    }
  }
}
```

At the beginning of your module file, say main.tf

This works for me.

**Comment by xiaozhu36** [comment]
@rsun-thoughtworks Using source `"aliyun/alicloud"` is ok.
