### ISSUE TITLE
new decarelation of a private zone attachment will replace legacy one. Better to be merged.

### ISSUE THREAD

**Issue by y-zh** [aliyun/terraform-provider-alicloud#3493]
[The example of private zone attchment ](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/pvtz_zone_attachment) shows how to attach multiple VPCs into a private zone.  However, in actual use, most cases should be attaching a new VPC into an existed private zone. I just found a new pvtz attachemnt will replace legacy one. I think it is better to merge, not replace.

Terraform version 0.15.0
alicloud provider version 1.121.2
Repro steps:
1.  declare a private zone and attach one vpc (vpc A)
2.  tf plan & apply 
3.  declare another attachment with another vpc (VPC B)
4.  tf plan & apply
5.  you will see vpc A is not attached.

btw, I'm trying to workaround by merging map but still failed.  Any idea how? Thanks.

**Comment by xiaozhu36** [comment]
HI. @y-zh I think you can attach several vpcs with one attachment, not using twice.

**Comment by y-zh** [comment]
Just like I mentioned. My case is to attach a new VPC to an existed private zone.  And my VPC creation is in a reusable module. I'd like to implement every VPC created in the module should be attached to one private zone.

**Comment by xiaozhu36** [comment]
I think you can merge the all of vpc ids into a variable and then use this variable to attach an existing private zone.

**Comment by y-zh** [comment]
I agree it is a possible workaround.  But I disagree it is a graceful one .  I have to expose VPC id from my module although it is unnecessary.  The workaround definitely brings complexity into my code.

you may refer  [CEN attachment ](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cen_instance_attachment)  , which is easier to use.

**Comment by y-zh** [comment]
Workaround is used to merge all pvtz in top level of tf.  All modules have to expose their own pvtz.  I close this issue but I think there should be more graceful solution.
