### ISSUE TITLE
alicloud_slb ShareSlbHaltSales

### ISSUE THREAD

**Issue by kwoodson** [aliyun/terraform-provider-alicloud#3517]
alicloud_slb is being deprecated. I do not see alicloud_clb or an alternative. This leaves terraform users in a bad state.  Please update the modules, documentation, and explain the migration to classic load balancers.

### Terraform Version
```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/alicloud v1.122.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)
alicloud_slb

### Terraform Configuration Files
```
resource "alicloud_slb" "slb" {
  name         = "ocp-slb"
  vswitch_id   = var.vswitch_id
  address_type = "internet"
}
```

### Debug Output
```
│ Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_slb.go:245: Resource alicloud_slb CreateLoadBalancer Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
│ SDK.ServerError
│ ErrorCode: ShareSlbHaltSales
│ Recommend: https://error-center.aliyun.com/status/search?Keyword=ShareSlbHaltSales&source=PopGw
│ RequestId: 5A12B329-D9BA-4B9A-801A-124A75BA3332
│ Message: The share instance has been discontinued.
│ 
│   with module.load_balancer.alicloud_slb.slb,
│   on load_balancer/lb.tf line 1, in resource "alicloud_slb" "slb":
│    1: resource "alicloud_slb" "slb" {
```
### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
This should recommend a migration to the classic load balancer or automatically create a classic load balancer. Print a deprecated message. Update the documentation to explain why this module is outdated and deprecated.

### Actual Behavior
Failure with message `The share instance has been discontinued.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `alicloud_slb`
1. `terraform apply`

### Important Factoids
Simple attempt to create an SLB.

**Comment by xiaozhu36** [comment]
Hi @kwoodson I am sorry for the late reply. The alicloud_slb has been deprecated by alicloud_slb_load_balancer: https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/slb_load_balancer. It is also clb.

About error ShareSlbHaltSales, which region is your setting? Currently, some region has discontinued the Shared-Performance Instance and you need to load_balancer_spec to set a available spec: https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/slb_load_balancer#load_balancer_spec

Please let me know if you have more issue.

**Comment by kwoodson** [comment]
@xiaozhu36 I was able to get passed this error by specifying the `specification` field and therefore not creating the shared load balancer.

https://github.com/kwoodson/terraform-openshift-alibaba/blob/master/load_balancer/lb.tf#L16

I'm still using `alicloud_slb`. I will update my code to move to the newer referenced `alicloud_slb_load_balancer`. Thanks!
