### ISSUE TITLE
support configuration of scan-interval for cluster autoscaler

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3551]
According to [the upstream documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca) the cluster-autoscaler has an option to set the `scan-interval` which defines in which interval the autoscaler checks if it needs to take action.

The upstream default for this is 10 seconds and it seems that alicloud forces a default of 30 seconds currently.

We would like to have this configurable, as 30 seconds is too long for our needs.

From my understanding this should be added to the [alicloud_cs_kubernetes_autoscaler](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_kubernetes_autoscaler) resource.

**Comment by anserhyb** [comment]
This feature is not yet supported, it is already in the plan, and it is expected to be supported at the end of June or early July.

**Comment by aschleifer** [comment]
This was added in 1.127.0
