### ISSUE TITLE
modify alicloud_ecs_disk plans to set values to null

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3612]
when modifying an existing alicloud_ecs_disk I see the following in the plan:

![image](https://user-images.githubusercontent.com/4940026/120820396-ca7c4a80-c554-11eb-863e-49f4acda894a.png)

It feels very strange for me that suddenly values that I didn't change are planned to be set to `null`. I have seen this also happen for `encrypted`.

Should I be worried about such "null changes" or are there kind of normal?

**Comment by xiaozhu36** [comment]
HI. @aschleifer I am sorry for the issue. I have checked the resource code and I will make a test for cloud_essd and fix it in the next version.

**Comment by xiaozhu36** [comment]
HI. @aschleifer This issue has been fixed by #3625  and it has been published in version 1.124.2. Please have a check.
