### ISSUE TITLE
cms alarm cannot accept 'Value' for staticistics parameter when applying on OSS mornitoring

### ISSUE THREAD

**Issue by y-zh** [aliyun/terraform-provider-alicloud#3613]
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cms_alarm
https://help.aliyun.com/document_detail/162870.html

Trying to create cms alarm for oss metric 'InternetSend'.  According to document,  Statistics parameter should be "Value". However, TF gives error that 'Value' is not acceptable

      resource "alicloud_cms_alarm" "alarm_oss_default_internet_send" {
          name    = "oss-default-internet-send"
          project = "acs_oss_dashboard"
          metric  = "InternetSend"
          dimensions = {
            resource = "_ALL"
          }
          escalations_critical {
            statistics          = **"Value"**
            comparison_operator = ">"
            threshold           = 2*1024*1024
            times               = 1
          }
          period         = 300  # 5 minutes
          silence_time   = var.default_cms_silence_time
          contact_groups = [var.sre_group_name] 
        }

### Terraform Version
0.15.5

### Affected Resource(s)
OSS Bucket Monitoring

### Expected Behavior
Alarm should be created.

### Actual Behavior
Creation failed due to error:
       │ Error: expected escalations_critical.0.statistics to be one of [Average Minimum Maximum ErrorCodeMaximum], got Value

### Steps to Reproduce
`terraform apply`

### References
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cms_alarm
https://help.aliyun.com/document_detail/162870.html

**Comment by xiaozhu36** [comment]
HI @y-zh It has been fixed by #3274 and it has been released in 1.124.1. Please update and have a check.
