### ISSUE TITLE
support configuration of cluster node pool "Scaling Mode" through terraform

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3629]
We would like to be able to control the "Scaling Mode" (Standard, Swift) via terraform. Currently this is only posisble via web console:
![image](https://user-images.githubusercontent.com/4940026/121926459-4721dc80-cd3e-11eb-94b5-f52d701d4a68.png)

**Comment by anserhyb** [comment]
Supported in version 1.127.0
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_kubernetes_node_pool#scaling_policy

**Comment by aschleifer** [comment]
confirmed. seems to work
