### ISSUE TITLE
Verison 1.124.4 changed after release and is now not usable anymore

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3672]
On Friday, 25.06.2021 at 17:58 o'clock I get an email that the release **1.124.4** is out:
![image](https://user-images.githubusercontent.com/4940026/123642158-43548680-d823-11eb-92e1-741e25bad01d.png)

Today when I work on one of our modules I decide to update to that version and get the following error from terraform:
```
Initializing provider plugins...
- Finding aliyun/alicloud versions matching "1.124.4"...
Error: Failed to install provider
Error while installing aliyun/alicloud v1.124.4: could not query provider
registry for registry.terraform.io/aliyun/alicloud: failed to retrieve
authentication checksums for provider: 404 Not Found
```

When I use **1.124.3** it works. Then I wanted to check if someone already reported this in this  repository.

Imagine my surprise when I see this on the right side of the repo:
![image](https://user-images.githubusercontent.com/4940026/123642317-71d26180-d823-11eb-8315-f2a2b7e8b8c9.png)

According to that information the version **1.124.4** doesn't exist (anymore). When I then click to releases I see this:
![image](https://user-images.githubusercontent.com/4940026/123642441-962e3e00-d823-11eb-9576-8cbbeb8ad266.png)

Which seems like someone **RETAGGED** again!!!! and removed the release notes and all build assets. From the terraform error it seems also that the checksum file is gone from the terraform registry.

When I click on that 1.124.4 release/tag I see this: https://github.com/aliyun/terraform-provider-alicloud/releases/tag/v1.124.4
![image](https://user-images.githubusercontent.com/4940026/123642668-da214300-d823-11eb-8033-0c201a574610.png)

When I look at the terraform page for the provider ( https://registry.terraform.io/providers/aliyun/alicloud/latest ) I see also **1.124.4**:
![image](https://user-images.githubusercontent.com/4940026/123642799-fb822f00-d823-11eb-8178-2fb57cd8b8ca.png)

**Why is this a problem?**
In general it is always bad to re-tag a version. Basically I expect that when I pull on Friday a version of the provider and then pull the same version on Monday that I expect both versions to have the same checksum and have the same code contained within.

Furthermore in case of a terraform provider (half) "deleting" a version as it happened here brings the following additional problem:

If I had updated our code on Friday to the version **1.124.4** I would have had a problem today as all our automatic CI pipelines would fail because they can't initialize the version anymore.

**_Please consider what you are doing and think about the consequences. Also test your changes. This isn't the first time that re-tagging happened on this repository._**

**Comment by xiaozhu36** [comment]
HI @aschleifer I am sorry for this issue. Now it has been fixed and I can ensure the issue will not happen again.
This issue comes from a github action workflow and it edited the latest release and led the published release been removed. Now, I have closed the workflow and re-published the version v1.124.4 and it is same as before.
