### ISSUE TITLE
希望增加 `alicloud_fc_version`

### ISSUE THREAD

**Issue by bingtsingw** [aliyun/terraform-provider-alicloud#3690]
目前函数计算无法用terraform创建版本, 导致自动化流程不完整, 希望能增加对应的resource
https://www.alibabacloud.com/help/zh/doc-detail/191160.htm

**Comment by bingtsingw** [comment]
我自己写了一个临时的版本, 供参考 https://github.com/bingtsingw/terraform-provider-aliyun/blob/main/aliyun/resource_aliyun_fc_version.go

**Comment by shinny-chengzhi** [comment]
阿里的接口只能对最新的代码创建版本，如果 terraform 描述中一次出现了多个新的版本会导致创建第二个版本失败，并不是很好用

**Comment by bingtsingw** [comment]
> 阿里的接口只能对最新的代码创建版本，如果 terraform 描述中一次出现了多个新的版本会导致创建第二个版本失败，并不是很好用

确实有这个问题, 我是用在第一次初始化的时候, 创建函数->版本->别名, 没有版本创建不了别名.
