### ISSUE TITLE
`alicloud_dcdn_domain` support `cname` export

### ISSUE THREAD

**Issue by bingtsingw** [aliyun/terraform-provider-alicloud#3693]
`alicloud_dcdn_domain` 应该返回 `cname`

**Comment by wowq** [comment]
这个有新的支持吗？要不然无法满足自动dns解析的需求

**Comment by bingtsingw** [comment]
> 这个有新的支持吗？要不然无法满足自动dns解析的需求

官方好像一直没支持, 自力更生吧, https://github.com/bingtsingw/terraform-provider-aliyun

**Comment by xiaozhu36** [comment]
@bingtsingw @wowq 非常抱歉回复晚了，给您带来了不好的使用体验。目前这个属性已经通过 [PR](https://github.com/aliyun/terraform-provider-alicloud/pull/5863) 增加上了，下个版本即可使用。

**Comment by bingtsingw** [comment]
> @bingtsingw @wowq 非常抱歉回复晚了，给您带来了不好的使用体验。目前这个属性已经通过 [PR](https://github.com/aliyun/terraform-provider-alicloud/pull/5863) 增加上了，下个版本即可使用。

谢谢大佬

**Comment by wowq** [comment]
感谢感谢
