### ISSUE TITLE
feature request: Data Transmission Service resources

### ISSUE THREAD

**Issue by cofyc** [aliyun/terraform-provider-alicloud#3751]
we'd hope the Data Transmission Service resources can be managed by terraform

https://help.aliyun.com/document_detail/211372.html

**Comment by rsun-thoughtworks** [comment]
Request too.

**Comment by tiankai66** [comment]
Your feedback has been received. We will process it as soon as possible.
Thank you for your trust and support of Alibaba Cloud!

**Comment by xiaozhu36** [comment]
HI @cofyc I am sorry for late reply. This service has been supported since provider version 1.157.0. Please update and have a try.
