### ISSUE TITLE
Provide options to enable/disable 'Alibaba Cloud OSS Private Bucket Access' in CDN

### ISSUE THREAD

**Issue by xuqingfeng** [aliyun/terraform-provider-alicloud#3819]
### Terraform Version
Terraform v0.13.6

### Affected Resource(s)
- alicloud_cdn_domain_new

![Screenshot 2021-08-09 at 15-07-29 Alibaba Cloud CDN](https://user-images.githubusercontent.com/3715820/128670681-46bd4c29-796c-4bbf-a851-638a41b1466b.png)

**Comment by tiankai66** [comment]
Your feedback has been received. We will process it as soon as possible.
Thank you for your trust and support of Alibaba Cloud!

**Comment by xiaozhu36** [comment]
HI @xuqingfeng This feature has been supported by resource [alicloud_cdn_domain_config](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cdn_domain_config) and you can config it as the following exampel:

```
resource "alicloud_cdn_domain_config" "default" {
  domain_name = "Your_Domain_Name"
  function_name = "l2_oss_key"
  function_args {
    arg_name = "private_oss_auth"
    arg_value = "on"
  }
}

```
