### ISSUE TITLE
alicloud_cs_kubernetes_node_pool doesn't see existing user_data

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3820]
If you create a managed node pool with `alicloud_cs_kubernetes_node_pool` with the field `user_data` set to some valid base64 encoded command then a `terraform plan` afterwards shows the `user_data` field as a new line (starting with a `+`), but if you query the node pool with the cli (`aliyun cs DescribeClusterNodePoolDetail --ClusterId=<cluster_id> --NodepoolId=<nodepool_id>`) you see in the response that the `user_data` is already set.

This change should not show up in `terraform plan`, if the `user_data` is already set to the node pool and doesn't change.

**Comment by tiankai66** [comment]
Your feedback has been received. We will process it as soon as possible.
Thank you for your trust and support of Alibaba Cloud!

**Comment by anserhyb** [comment]
Limited by the design of the product, the update of the node pool configuration parameters (not only user_data) can only be applied to newly generated nodes. The existing nodes will not be updated synchronously.

**Comment by aschleifer** [comment]
I know that updates only will affect new nodes which are spawned after the change was applied.

But we are talking here about nodepool level. We define a nodepool resource and this has the user_data defintion. When I then run `terraform apply` again on the same nodepool resource I would expect no change. But instead i see the same user_data field being added again as new to the nodepool resource.

This causes an update for the resource during `terraform apply` which is unnecessary and only increases the time it takes to run the `terraform apply`.
