### ISSUE TITLE
add option to disable autoscaling for existing managed alicloud_cs_kubernetes_node_pool

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3822]
Currently there is no way to disable autoscaling for existing managed `alicloud_cs_kubernetes_node_pool`'s as this gets always enabled upon change in the terraform provider.
We would like to have the `enable` flag from the API also in the `scaling_config` of the `alicloud_cs_kubernetes_node_pool` resource.

**Comment by tiankai66** [comment]
Your feedback has been received. We will process it as soon as possible.
Thank you for your trust and support of Alibaba Cloud!
Could you kindly provide the related API doc link or use cases?

**Comment by tbalzer** [comment]
As for API please see https://www.alibabacloud.com/help/doc-detail/184625.htm and the related updating API.

As for use-case, you may see e.g. #3821 for a case in which we would want to have this feature to be able to "repair" our node pools.
Also in general this should be possible as it is available in the API and logically already possible in terraform (removing the scaling_config should do this, but it just would not work based on the current configuration).

**Comment by tiankai66** [comment]
Received， thanks for your feedback!
