### ISSUE TITLE
terraform apply fails when creating professional cluster with multiple managed node pools

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3833]
If you create a professional kubernetes cluster with more then one managed node pool the `terraform apply` failes:

```
alicloud_cs_kubernetes_node_pool.core: Still creating... [3m0s elapsed]
alicloud_cs_kubernetes_node_pool.core: Still creating... [3m10s elapsed]
alicloud_cs_kubernetes_node_pool.core: Still creating... [3m20s elapsed]
alicloud_cs_kubernetes_node_pool.core: Creation complete after 3m26s [id=c828d583172944f039635f00dced7c3d2:npb02781fad3a447bcb37c64afa0116a67]
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_kubernetes_node_pool.go:434: Resource alicloud_cs_kubernetes_node_pool CreateKubernetesNodePool Failed!!! %!s(*cs.CreateNodePoolResponse=<nil>):
Aliyun API Error: RequestId:  Status Code: 400 Code: InvalidStatus.Forbidden Message: cannot operate cluster where state is scaling
  on main.tf line 143, in resource "alicloud_cs_kubernetes_node_pool" "autoscaling":
 143: resource "alicloud_cs_kubernetes_node_pool" "autoscaling" {
```

So it sems the API call to create the first node pool (which we named "core" returns that it is done, but the cluster itself still is in a "scaling" state. Then TF tries to start the creation of the second node pool (which we named "autoscaling") but this fails as the API call returns that the cluster is still scaling.

Rerunning the pipeline again afterwards works and creates the second node pool without issues.

**Comment by anserhyb** [comment]
The ACK server restricts the creation of multiple node pools at the same time, and a dependency needs to be added to TF to allow the node pools to be created serially. Example:
`resource "alicloud_cs_kubernetes_node_pool" "nodepool-foo" {
  # required parameters for node pool
}

resource "alicloud_cs_kubernetes_node_pool" "nodepool-bar" {
  # required parameters for node pool
  depends_on = [
    alicloud_cs_kubernetes_node_pool.nodepool-foo
  ]
}`

**Comment by anserhyb** [comment]
When a node pool is created, the status of the cluster is updated. During status migration, other cluster operations, including node pool creation, are denied. A node pool can be created one by one. You can't create the second one until the first one is finished.
Secondly. Although it is serial in TF, there is no resource reference relationship between the two node pools. TF will create both resources at the same time.

**Comment by aschleifer** [comment]
But the output of the `terraform apply` I posted shows clearly that TF says the first node pool was successfully create before TF tries to create the second one which then crashes.

**Comment by aschleifer** [comment]
@anserhyb  you were right. Even so the output looked already as if it was executing the creations of the node pools in sequence apparently it did not. I added the dependency as you suggested and now the `terraform apply` runs through in the first run.

Thanks for the suggestion and sorry for the inconvenience.
