### ISSUE TITLE
Support hostname field in alicloud_ess_scaling_configuration

### ISSUE THREAD

**Issue by bittopaz** [aliyun/terraform-provider-alicloud#3892]
This is a feature request. A good use case can be seen in https://help.aliyun.com/document_detail/203831.htm

### Affected Resource(s)
alicloud_ess_scaling_configuration

**Comment by lorenzogherdovich** [comment]
Yes, I was looking for the same. feature++

**Comment by lorenzogherdovich** [comment]
it works in 1.143.0.

Thank you all.

**Comment by bittopaz** [comment]
@lorenzogherdovich Thank you very much for adding this.
