### ISSUE TITLE
Feature Request:  specify a KMS key with alicloud_cs_managed_kubernetes to encrypt Kubernetes Secrets

### ISSUE THREAD

**Issue by mick1627** [aliyun/terraform-provider-alicloud#3910]
Hi there,

Currently there is no parameter to specify a KMS key to use keys that are created in Key Management Service (KMS) to encrypt Kubernetes Secrets with the ressource alicloud_cs_managed_kubernetes.

Affected Resource(s)
Please list the resources as a list, for example:

alicloud_cs_managed_kubernetes

**Comment by anserhyb** [comment]
This is what you want. https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_managed_kubernetes#kms_encrypted_password

**Comment by mick1627** [comment]
I found it https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_managed_kubernetes#encryption_provider_key
