### ISSUE TITLE
defining alicloud_db_account_privilege for two users on the same postgresql db causes state flapping

### ISSUE THREAD

**Issue by aschleifer** [aliyun/terraform-provider-alicloud#3990]
We have an RDS postgresql instance created with `alicloud_db_database` and then two accounts (lets call them "accountA" and "accountB") with `alicloud_rds_acocunt`. We then grant "DBOwner" privileges to both of these accounts on the same list of databases (db_names) on that instance using `alicloud_db_account_privilege`.

Applying this with terraform seems fine from a functional state. both accounts have their privileges and work correctly. Also the web UI shows both accounts have access to that database on the instance.

However when I run a subsequent apply i suddenly see the following change in the `terraform plan` output:
```
  # alicloud_db_account_privilege.privilege[1] will be updated in-place
  ~ resource "alicloud_db_account_privilege" "privilege" {
        account_name = "accountB"
      ~ db_names     = [
          + "my_database",
        ]
        id           = "pgm-4xo7k6a8vaoymolp:accountB:DBOwner"
        instance_id  = "pgm-4xo7k6a8vaoymolp"
        privilege    = "DBOwner"
    }
```

When I apply this every thing still works but another `terraform plan` then shows this output:
```
  # alicloud_db_account_privilege.privilege[0] will be updated in-place
  ~ resource "alicloud_db_account_privilege" "privilege" {
        account_name = "accountA"
      ~ db_names     = [
          + "my_database",
        ]
        id           = "pgm-4xo7k6a8vaoymolp:accountA:DBOwner"
        instance_id  = "pgm-4xo7k6a8vaoymolp"
        privilege    = "DBOwner"
    }
```

And this goes on and on. So it seems the provider always only sees one of the two accounts properly setup.

Technical information:
Terraform version: 0.13.7
provider version: 1.121.2

**Comment by tiankai66** [comment]
Your feedback has been received. We will process it as soon as possible.
Thank you for your trust and support of Alibaba Cloud!

**Comment by aschleifer** [comment]
Turns out there can be only one DBOwner for postgresql dbs.
