### ISSUE TITLE
[issue] Unable to create alert contact with TF code

### ISSUE THREAD

**Issue by gmi-vishal** [aliyun/terraform-provider-alicloud#4074]
### Terraform Version
  Terraform v0.14.11

### Affected Resource(s)
  alicloud_arms_alert_contact

### Terraform Configuration Files
```hcl

resource "alicloud_arms_alert_contact" "alert-contact" {
    alert_contact_name = "test"
    email              = "test@abc.com"
}
```

### Expected Behavior
It should create a alert contact in host monitoring

### Actual Behavior
It just say resource created but does not create any contact in alert contact windows

### Steps to Reproduce
 `terraform apply`  above code
It get applied, check output of apply and then check in console.
alert contact does not get created

**Comment by gmi-vishal** [comment]
@tiankai66

**Comment by gmi-vishal** [comment]
@tiankai66  Any update on this ??

**Comment by tiankai66** [comment]
hello, you should use cms alert contact for searching, not arms alert contact. they are two different resources.

**Comment by gmi-vishal** [comment]
Thanks, I was checking in wrong windows :(
