### ISSUE TITLE
Unable to set private port of RDS Posgtres instance

### ISSUE THREAD

**Issue by pnjha** [aliyun/terraform-provider-alicloud#4132]
### Terraform Version
Terraform v1.0.9

### Affected Resource(s)
alicloud_db_instance

### Terraform Configuration Files
```
"terraform": {
    "required_providers": {
      "alicloud": {
        "source": "aliyun/alicloud",
        "version": "1.139.0"
      }
    }
  },
```
```
"alicloud_db_instance": {
      "rds_postgresql_instance": {
        "engine": "PostgreSQL",
        "engine_version": "12.0",
        "instance_type": "pg.n2.small.2c",
        "instance_storage": 20,
        "db_instance_storage_type": "cloud_ssd",
        "db_time_zone": "Etc/UTC",
        "sql_collector_status": "Disabled",
        "instance_name": "pg2",
        "instance_charge_type": "Postpaid",
        "zone_id": "eu-central-1a",
        "port": "2346",
        "vswitch_id": "<redacted>",
        "security_ip_mode": "safety",
        "maintain_time": "22:00Z-03:00Z",
        "ssl_action": "Open",
        "encryption_key": "",
        "timeouts": {
          "create": "60m",
          "update": "60m",
          "delete": "60m"
        }
      }
    }
```

### Expected Behavior
Postgresql instance should be created with the private port mentioned in the template but it is created with port 5432 always.

### Actual Behavior
I am using the above JSON terraform template to create a PostgreSQL instance. Notice I have set port to 2346 but after the instance is created port is always set to 5432 and also in the tfstate failed port is set to 5432. Only the next time I do terraform apply port is getting set to the required value I am passing in the template. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Try creating a terraform template with the port as any valid value other than 5432
2. Perform `terraform apply`
3. Check tfstate file for the port value. It will be 5432.
4. Perform `terraform apply` again
5. Check tfstate file for the port value. It will be the value mentioned in the template.

**Comment by tiankai66** [comment]
hello, we have already reproduced this issue, pe team is working on it.
