### ISSUE TITLE
How to define the Categray of RDS MySQL? 

### ISSUE THREAD

**Issue by wwyhy** [aliyun/terraform-provider-alicloud#4151]
Hi there,

We are trying to create a RDS MySQL with High Avalibility according to document.
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/db_instance#engine_version

There is a Categray to define which type we can create in below link. 
https://www.alibabacloud.com/help/doc-detail/26228.htm

`Category -> Value：Basic, HighAvailability：HighAvailabilityAlwaysOn：Cluster, Finance
`

So how can we specify the Categray? 

Thanks!

**Comment by pnjha** [comment]
Category is determined by instance type of RDS MySQL. You can refer to this doc: https://www.alibabacloud.com/help/doc-detail/276975.htm?spm=a2c63.p38356.879954.6.566e7670AqZCaC#concept-2096487

**Comment by wwyhy** [comment]
Got it, thanks!
