### ISSUE TITLE
[Feature Request] Need resource to create address book (Cloud firewall) resource with Terraform

### ISSUE THREAD

**Issue by gmi-vishal** [aliyun/terraform-provider-alicloud#4338]
Hi Ali Team,

It would be great if we can get resource for address book creation in Ali Cloud Firewall. 
Currently we can just have a option to create a Firewall instance, Create a policy and order policy. 

@xiaozhu36

**Comment by xiaozhu36** [comment]
Hi @gmi-vishal Got it. I have added it to our requirement list and will schedule to support it.

**Comment by rsun-thoughtworks** [comment]
> Hi @gmi-vishal Got it. I have added it to our requirement list and will schedule to support it.

What is the plan now?

**Comment by gmi-vishal** [comment]
@xiaozhu36  any update on this ??

**Comment by gmi-vishal** [comment]
> Hi @gmi-vishal Got it. I have added it to our requirement list and will schedule to support it.

Any update on this ??

**Comment by xiaozhu36** [comment]
Hi @gmi-vishal I am sorry for late reply and it has been supported by version 1.178.0 and refer to https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cloud_firewall_address_book
