### ISSUE TITLE
data "terraform_remote_state" can't get credential

### ISSUE THREAD

**Issue by jianglei-els** [aliyun/terraform-provider-alicloud#4938]
Hi there,

### Terraform Version
1.1.9
alicloud provider 1.165.0

### Affected Resource(s)
Please list the resources as a list, for example:
- data "terraform_remote_state" 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
data "terraform_remote_state" "network" {
    backend   = "oss"
    config    = {
        bucket = "mytfstate"
        key    = "terraform.tfstate"
        prefix = "prod-a/prod/srv1"
        region = "cn-shanghai"
        encrypt = true
    }
    #outputs   = {}
    #workspace = "default"
}

### Debug Output
NA

### Panic Output
Error: describe oss endpoint using region: "cn-shanghai" got an error: &errors.ServerError{RespHeaders:map[string][]string{"Access-Control-Allow-Headers":[]string{"X-Requested-With, X-Sequence, _aop_secret, _aop_signature, x-acs-action, x-acs-version, x-acs-date, Content-Type"}, "Access-Control-Allow-Methods":[]string{"POST, GET, OPTIONS, PUT, DELETE"}, "Access-Control-Allow-Origin":[]string{"*"}, "Access-Control-Max-Age":[]string{"172800"}, "Content-Length":[]string{"264"}, "Content-Type":[]string{"application/json;charset=utf-8"}, "Date":[]string{"Fri, 06 May 2022 11:41:55 GMT"}, "X-Acs-Request-Id":[]string{"E450F731-A16A-3751-9070-238612BFDD3A"}, "X-Acs-Trace-Id":[]string{"fc27d31bef25381946274596a34679c7"}}, httpStatus:400, requestId:"E450F731-A16A-3751-9070-238612BFDD3A", hostId:"location-readonly.aliyuncs.com", errorCode:"MissingAccessKeyId", recommend:"https://troubleshoot.api.aliyun.com?q=MissingAccessKeyId&product=Location", message:"AccessKeyId is mandatory for this action.", comment:""}

### Expected Behavior
Should authorized with one of following credential method, but all I tested non of them work.
1. AK/SK in provider.tf
2. aliyun configure --mode AK
3. aliyun configure --mode ECSRAMRole
4. Aliyun credentials in environments ALIBABA_CLOUD_ACCESS_KEY_ID and ALIBABA_CLOUD_ACCESS_KEY_SECRET

### Actual Behavior
Failed with AK not setting, and wrong host id "location-readonly.aliyuncs.com"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. use OSS as backend to provision any resource, eg. a VPC
2. `terraform plan` with above data.tf config, to read out the remote states in same OSS bucket key.

### Important Factoids
NA

### References
Don't know

**Comment by xiaozhu36** [comment]
HI @jianglei-els The error shows the terraform_remote_state config missing credential setting. You can add the setting in the config and have a try, like this:

```
data "terraform_remote_state" "network" {
backend = "oss"
config = {
access_key = xxx
secret_key = xxx
bucket = "mytfstate"
key = "terraform.tfstate"
prefix = "prod-a/prod/srv1"
region = "cn-shanghai"
encrypt = true
}
#outputs = {}
#workspace = "default"
}
```
or, if you want to use ECSRAMRole:

```
data "terraform_remote_state" "network" {
backend = "oss"
config = {
ecs_role_name = xxx
bucket = "mytfstate"
key = "terraform.tfstate"
prefix = "prod-a/prod/srv1"
region = "cn-shanghai"
encrypt = true
}
#outputs = {}
#workspace = "default"
}
```

**Comment by jianglei-els** [comment]
Thank you, it works now.
