### ISSUE TITLE
terraform init

### ISSUE THREAD

**Issue by guleng** [aliyun/terraform-provider-alicloud#5655]
Hi there,

### Terraform Version 1.3.5

我要terraform init时都不能顺利下载，有没有什么办法能快速init吗？
![jjj](https://user-images.githubusercontent.com/40238640/205494762-47d06d13-c72a-429f-93fc-f7fe8c8d25c5.png)

有推荐的方法能提供帮助吗？

**Comment by xiaozhu36** [comment]
@guleng 你好，现在有两个临时方案：
1. 可以尝试切换为 source = hashicorp/alicloud，这个有时候会稍好一些，但是也不能保证一定可行
2. 可以尝试在本地构建一个缓存目录，这样在下载的时候会从缓存目录中去下载，详见：https://developer.hashicorp.com/terraform/cli/config/config-file#implied-local-mirror-directories，但是这个在下载的时候，也会访问 registry.terraform.io 的API去获取相关的元数据，所以也不能保证一定可行。

目前，针对这个问题，我们考虑在国内提供相关的镜像站，也正在跟社区就行沟通，一旦国内有镜像站了，这个问题就可以彻底解决了。

**Comment by guleng** [comment]
非常有用  感谢
