### ISSUE TITLE
Error: The terraform-provider-alicloud_v1.196.0.exe plugin crashed!

### ISSUE THREAD

**Issue by chkp-falehk** [aliyun/terraform-provider-alicloud#5876]
Hi,
Terraform aliyun provider crash upon destroying the ram role,  "Error: The terraform-provider-alicloud_v1.196.0.exe plugin crashed!"
This issue is happening always, tried to use several other providers but no progress,
Can you assist with this issue, its very critical for production,

module.launch_cluster_into_vpc.module.common_member_a_mgmt_eip.alicloud_eip.instance_eip[0]: Destroying... [id=eip-]
module.launch_cluster_into_vpc.alicloud_network_interface.member_b_internal_eni: Destroying... [id=eni-]
module.launch_cluster_into_vpc.module.common_member_b_mgmt_eip.alicloud_eip.instance_eip[0]: Destroying... [id=eip-]
module.launch_cluster_into_vpc.module.common_cluster_secondary_eip.alicloud_eip.instance_eip[0]: Destroying... [id=eip-]
module.launch_cluster_into_vpc.module.cluster_ram_role[0].alicloud_ram_role.ram_role: Destroying... [id=]
module.launch_cluster_into_vpc.alicloud_network_interface.member_a_internal_eni: Destroying... [id=eni-]
module.launch_cluster_into_vpc.module.common_cluster_primary_eip.alicloud_eip.instance_eip[0]: Destroying... [id=]
module.launch_cluster_into_vpc.module.cluster_ram_role[0].alicloud_ram_policy.ram_policy: Destroying... [id=]
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully
│ updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵ Stack trace from the terraform-provider-alicloud_v1.196.0.exe plugin: panic: interface conversion: interface {} is nil, not []interface {} goroutine 115 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudRamPolicyDelete(0xc00163e460, {0x728c780?, 0xc000517c00})
        github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_ram_policy.go:301 +0x2094
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000fdce00, 0xc0009f45f0, 0xc00132f400, {0x728c780, 0xc000517c00})
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:278 +0x257
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00198ee80, 0xc0017af960, 0x72e7019?, 0xf?)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000063f0, {0xc000907620?, 0xea1406?}, 0xc000907620)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:885 +0x79d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x6bacb00?, 0xc0000063f0}, {0x7bbd248, 0xc001632bd0}, 0xc0009075c0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005ac780, {0x7c070c8, 0xc000207980}, 0xc0018fc800, 0xc0019bc0f0, 0xd964a80, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0005ac780, {0x7c070c8, 0xc000207980}, 0xc0018fc800, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xea 
Error: The terraform-provider-alicloud_v1.196.0.exe plugin crashed! 
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by xiaozhu36** [comment]
HI @chkp-falehk I am sorry for the late reply and the issue. This issue has been fixed on the provider version 1.203.0. Please upgrade it and have a try. Please let me know and reopen the issue if you have more problems.
