### ISSUE TITLE
[Feature Request] OSS Lifecycle Transitions support "Cold Archive" type

### ISSUE THREAD

**Issue by hjweddie** [aliyun/terraform-provider-alicloud#5897]
OSS support "Cold Archive" storage type for a long time, and we can set lifecycle transitions with cod archive type in web console. Hope that we can also do it with terraform provider

**Comment by xiaozhu36** [comment]
@huiguangjun Please have a check.

**Comment by xiaozhu36** [comment]
Hi @hjweddie I am sorry for late reply. It has been supported by 1.209.0, and please update it and have a try.
