### ISSUE TITLE
站点监控任务类型常量与API返回结果的大小写不一致

### ISSUE THREAD

**Issue by zhangyoufu** [aliyun/terraform-provider-alicloud#5960]
https://github.com/aliyun/terraform-provider-alicloud/blob/c97bd7b7278dc9afa96189827b87f4240f27f02f/alicloud/extension_cms.go#L23-L32

SiteMonitorPing 应修改为全部大写的 `"PING"`。目前 API 返回的 task_type 全大写，与本地状态不一致。

### Affected Resource(s)
- alicloud_cms_site_monitor

**Comment by xiaozhu36** [comment]
HI @zhangyoufu I am sorry for late reply. This issue has been fixed by 1.201.2 . Please update it and have a try again.
