### ISSUE TITLE
v1.201 vSwitch The plugin.(*GRPCProvider).ReadResource request was cancelled.

### ISSUE THREAD

**Issue by dirol13** [aliyun/terraform-provider-alicloud#5994]
### Terraform Version
terraform version 1.2.9

### Affected Resource(s)
vSwitch

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

panic: runtime error: index out of range [1] with length 1

goroutine 133 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudVswitchRead(0xc0000ef730, {0x69fb740?, 0xc00244a400?})
	github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_vswitch.go:186 +0x54a
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000eac800, 0xc001bf3ae0, {0x69fb740, 0xc00244a400})
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:455 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000420658, {0xc001bf39f0?, 0x526c06?}, 0xc001bf39f0)
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:525 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x631b1a0?, 0xc000420658}, {0x733dce0, 0xc001cd9b00}, 0xc001e488a0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00078ed80, {0x7387b48, 0xc000235980}, 0xc001b89100, 0xc001993c80, 0xd114b90, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc00078ed80, {0x7387b48, 0xc000235980}, 0xc001b89100, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xea

Error: The terraform-provider-alicloud_v1.201.0 plugin crashed!

### Expected Behavior
Should be working fine

### Actual Behavior
│ Error: Request cancelled
│ 
│   with module.ali_vpc.alicloud_vswitch.nat[0],
│   on ../terraform-modules/modules/ali_vpc/main.tf line 36, in resource "alicloud_vswitch" "nat":
│   36: resource "alicloud_vswitch" "nat" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.ali_vpc.alicloud_vswitch.utility[0],
│   on ../terraform-modules/modules/ali_vpc/main.tf line 149, in resource "alicloud_vswitch" "utility":
│  149: resource "alicloud_vswitch" "utility" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Worked fine in alicloud_v1.200

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by xiaozhu36** [comment]
HI @dirol13 I am sorry for this issue and it has been fixed from the 1.200.1. Please update it and have a try again.

Please reopen it if there are more issues.
