### ISSUE TITLE
Create OIDC provider using terraform

### ISSUE THREAD

**Issue by nickjosph** [aliyun/terraform-provider-alicloud#6027]
Is there a resource available in terraform that helps to create and configure an OIDC provider for Ali Cloud?

**Comment by xiaozhu36** [comment]
HI @nickjosph I am sorry for late reply, and thanks for your patient. The feature has been supported by version 1.222.0, and please refer to [assuming-a-ram-role-with-oidc](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs#assuming-a-ram-role-with-oidc)
