### ISSUE TITLE
Issue when I want to destroy NLB resources (Stuck TFE run and on pending loop configuration in Alibaba GUI Cloud Console)

### ISSUE THREAD

**Issue by Morichemont** [aliyun/terraform-provider-alicloud#6028]
Hi there,

I need to deploy and test NLB, available from 1.191.1+. Last week I update the version in 1.201.1 for that as you can see in the repo.

However we encountered issues when we tried to remove all NLB resources. It seems there's an issue with the order when the resource are evaluated and destroyed (I mean security group is deleted before the security attachment...)

After this task the plugin is crashed systematically and the only way to remove the issue, is to release the job stuck in TFE and ask Alibaba support to release the NLB instance stucks in "updating configuration" step.

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

In attachement....

### Expected Behavior

The different NLB resources should remove without any issues

### Actual Behavior

Error: The terraform-provider-alicloud_v1.199.0 plugin crashed!

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create NLB Loadbalancer
2. Create NLB Listener
3. Create NLB Server Group
4. Create NLB security group
5. Create NLB security groupe attachement
6. After the whole creation of each reources, try to remove the file and remove them in one API Call, that crash the plugin in 1.199.0, 1.201.1 and I think all version of the plugin...

### Ticket on Alibaba support

Ticket No.1Z1GYAM6
--

Thanks
Morgan

**Comment by Morichemont** [comment]
[run-hESaRq7fv2Bvybbf-plan-log.txt](https://github.com/aliyun/terraform-provider-alicloud/files/11079017/run-hESaRq7fv2Bvybbf-plan-log.txt)

<img width="1385" alt="Screenshot 2023-03-27 at 15 11 29" src="https://user-images.githubusercontent.com/129072705/227948815-6927a7c5-9482-40c5-9933-8c053e6c2a2a.png">

**Comment by Morichemont** [comment]
Hi everyone,

Nobody took this task in consideration ?

Thanks
Regards

**Comment by xiaozhu36** [comment]
HI @Morichemont This issue has been fixed by [PR-6052](https://github.com/aliyun/terraform-provider-alicloud/issues/6052), and the version 1.203.0 has contains it. Please update it and have a try again.

Please reopen it if you have more problems.
