### ISSUE TITLE
v1.203 module_alicloud_dns_record failed to respond to the plugin. (*GRPCProvider).ApplyResourceChange - panic: strconv.Atoi: parsing "2168897205": value out of range

### ISSUE THREAD

**Issue by NoodyYeung** [aliyun/terraform-provider-alicloud#6087]
### Terraform Version
terraform version 1.4.4

### Instance operation system
RedHat 8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_pvtz_zone_record

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
After running terraform apply, I got the following panic output.

Error: Plugin did not respond

  with alicloud_disk_attachment.sgp-m-workload-d01-vm001,
  on main.tf line 383, in resource "alicloud_disk_attachment" "sgp-csky-m-workload-d01-vm001":
 383: resource "alicloud_disk_attachment" "sgp-csky-m-workload-d01-vm001" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Error: Plugin did not respond

  with module.alicloud_dns_sgp-m-workload-d01-vm001.alicloud_pvtz_zone_record.dns_record,
  on module_alicloud_dns_record/main.tf line 8, in resource "alicloud_pvtz_zone_record" "dns_record":
   8: resource "alicloud_pvtz_zone_record" "dns_record" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-alicloud_v1.203.0 plugin:

panic: strconv.Atoi: parsing "2168897205": value out of range

goroutine 255 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.formatInt({0xd40ab60, 0x166c1140})
	github.com/aliyun/terraform-provider-alicloud/alicloud/common.go:1034 +0x354
github.com/aliyun/terraform-provider-alicloud/alicloud.(*PvtzService).DescribePvtzZoneRecord(0x1682da58, {0x166573b0, 0x2b})
	github.com/aliyun/terraform-provider-alicloud/alicloud/service_alicloud_pvtz.go:166 +0xa45
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudPvtzZoneRecordUpdate(0x160b4140, {0xdfcf580, 0x16a406c0})
	github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_pvtz_zone_record.go:190 +0x12d
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAlicloudPvtzZoneRecordCreate(0x160b4140, {0xdfcf580, 0x16a406c0})
	github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_pvtz_zone_record.go:153 +0x91b
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x15d7b080, 0x16abdad0, 0x166ad1b8, {0xdfcf580, 0x16a406c0})
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:305 +0x4fb
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x162caa50, 0x1682dc94, 0x16abdad0, 0x166ad1b8)
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/provider.go:294 +0x7d
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x16431380, {0xe9604d0, 0x166acac8}, 0x16abd980)
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:885 +0x889
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd9ffa20, 0x16431380}, {0xe9604d0, 0x166acac8}, 0x16abd950, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1570c6c0, {0xe989170, 0x158a7e00}, 0x166b1680, 0x15d62318, 0x142898a0, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1297 +0xc13
google.golang.org/grpc.(*Server).handleStream(0x1570c6c0, {0xe989170, 0x158a7e00}, 0x166b1680, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.40.0/server.go:941 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.40.0/server.go:939 +0x25f

Error: The terraform-provider-alicloud_v1.203.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior
Should working fine.

### Actual Behavior
The alicloud private zone record can be found on the alicloud console, but the log of "terraform apply" show the errors.

Error: Plugin did not respond

  with alicloud_disk_attachment.sgp-csky-m-workload-d01-vm001,
  on main.tf line 383, in resource "alicloud_disk_attachment" "sgp-csky-m-workload-d01-vm001":
 383: resource "alicloud_disk_attachment" "sgp-csky-m-workload-d01-vm001" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Error: Plugin did not respond

  with module.alicloud_dns_sgp-csky-m-workload-d01-vm001.alicloud_pvtz_zone_record.dns_record,
  on module_alicloud_dns_record/main.tf line 8, in resource "alicloud_pvtz_zone_record" "dns_record":
   8: resource "alicloud_pvtz_zone_record" "dns_record" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create a private zone record in main.tf
2. `terraform apply`

### Important Factoids
Also not working in 1.200.0

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by xiaozhu36** [comment]
Hi @NoodyYeung This issue has been fixed by the version 1.204.1. Please update and have a retry.
