### ISSUE TITLE
[feature-request] kvstore hopes to support redis 7.0

### ISSUE THREAD

**Issue by jesnridy** [aliyun/terraform-provider-alicloud#6105]
https://github.com/aliyun/terraform-provider-alicloud/blob/master/alicloud/data_source_alicloud_kvstore_instances.go#L56

The maximum version is currently limited to 6.0, hopefully it will support version 7.0.

**Comment by xiaozhu36** [comment]
HI. @jesnridy This feature has been supported by version 1.204.0. Please update it and have a try.
