### ISSUE TITLE
error on importing security_group_rule

### ISSUE THREAD

**Issue by QQLOVE123** [aliyun/terraform-provider-alicloud#6179]
D:\gitlab\service>terraform import module.ecs_secgroup.alicloud_security_group_rule.main[0] sgr-uf6bgkddsi9towp
data.alicloud_resource_manager_resource_groups.main: Reading...
data.alicloud_resource_manager_resource_groups.main: Read complete after 0s [id=1617825701]
data.alicloud_vpcs.main: Reading...
data.alicloud_vpcs.main: Read complete after 1s [id=1099642683]
module.ecs_secgroup.alicloud_security_group_rule.main[0]: Importing from ID "sgr-uf6bgkddsi9towp"...
module.ecs_secgroup.alicloud_security_group_rule.main[0]: Import prepared!
  Prepared alicloud_security_group_rule for import
module.ecs_secgroup.alicloud_security_group_rule.main[0]: Refreshing state... [id=sgr-uf6bgkddsi9towp]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-alicloud_v1.204.0.exe plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 49 [running]:
github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAliyunSecurityGroupRuleRead(0xc0023ff9d0, {0x6ce5f20?, 0xc0020cb000})
        github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_security_group_rule.go:294 +0xa71
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000f2c780, 0xc002093040, {0x6ce5f20, 0xc0020cb000})
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/helper/schema/resource.go:455 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000902d20, {0xc002092e10?, 0x711406?}, 0xc002092e10)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/helper/plugin/grpc_provider.go:525 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x6603e80?, 0xc000902d20}, {0x76af9c8, 0xc0020a37d0}, 0xc000982180, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.4.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005ff880, {0x76f9af8, 0xc0009a4180}, 0xc0020a0a20, 0xc001a53c80, 0xd4ee370, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0005ff880, {0x76f9af8, 0xc0009a4180}, 0xc0020a0a20, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x28a

Error: The terraform-provider-alicloud_v1.204.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by xiaozhu36** [comment]
HI @QQLOVE123 Thanks for your feedback and patient. Currently, the provider does not support importing resource `alicloud_security_group_rule`, and we will support it soon. I will let you know after doing it.

**Comment by xiaozhu36** [comment]
HI @QQLOVE123 This feature has been supported from the latest version [1.224.0](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/security_group_rule#import), and please update the version and have a try.
