### ISSUE TITLE
throw error when import slb to resource 

### ISSUE THREAD

**Issue by QQLOVE123** [aliyun/terraform-provider-alicloud#6195]
excute comman as :
terraform import module.main_slb.alicloud_slb_load_balancer.slb["slb001"] lb-uf6s54re21ew9u1dihs77a

![image](https://github.com/aliyun/terraform-provider-alicloud/assets/22112950/0585451a-6048-4a7b-9de1-9d39d519ab95)

**Comment by xiaozhu36** [comment]
HI @QQLOVE123 You can use the escape character or single quote to avoid the issue, like:

```
terraform import module.main_slb.alicloud_slb_load_balancer.slb["\"slb001\""] lb-uf6s54re21ew9u1dihs77a
```
or
```
terraform import module.main_slb.alicloud_slb_load_balancer.slb['"slb001"'] lb-uf6s54re21ew9u1dihs77a
```
