### ISSUE TITLE
throw error when create resource 

### ISSUE THREAD

**Issue by QQLOVE123** [aliyun/terraform-provider-alicloud#6196]
command:
resource "alicloud_slb_acl_entry_attachment" "attachment" {
  for_each = var.acl_list
  dynamic "entry_attachment" {
    for_each = each.value.entry
    content {
      acl_id     = alicloud_slb_acl.example[each.key].id
      entry      = entry_attachment.value
      comment    = each.value.comment
      ip_version = each.value.ip_version
    }
  }
}

error:
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/22112950/8eab7d51-f3a0-4e2b-a43a-05d2b5ba4c47)

**Comment by MrWolong** [comment]
The value of field entry is incorrect，pls check the structure of variable acl_list, and refer to terraform docs.
Terraform docs：https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/36806235/42f05a68-d8b8-4ac6-a092-72d516e40cd3)
![image](https://github.com/aliyun/terraform-provider-alicloud/assets/36806235/ba5ea918-6b7d-435e-a480-d4d783f2a34f)

**Comment by ChenHanZhang** [comment]
This issue has not been updated for a year, so we will close it. If you have other questions, please raise a new issue.
