### ISSUE TITLE
[feature-request] add resource_group_id to resource_alicloud_oss_bucket

### ISSUE THREAD

**Issue by gain620** [aliyun/terraform-provider-alicloud#6670]
Hi there,

Is it possible to add "resource_group_id" to the "resource_alicloud_oss_bucket"?

I want to explicitly specify which resource group my OSS bucket is in using Terraform, but currently, I have to go into the Alibaba Cloud console and change it manually.

<img width="873" alt="스크린샷 2023-11-17 오후 8 00 34" src="https://github.com/aliyun/terraform-provider-alicloud/assets/6823167/4c378233-5085-4590-a0bd-8ab9ea3ff9c0">

**Comment by xiaozhu36** [comment]
Hi @gain620 I am sorry for late reply. This feature has been supported by release 1.219.0, and please refer it:https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/oss_bucket#resource_group_id
