### ISSUE TITLE
The resource alicloud_ess_scaling_group missed the resource_group_id parameter

### ISSUE THREAD

**Issue by ik8svip** [aliyun/terraform-provider-alicloud#6671]
### Terraform Version

```bash
$ Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/aliyun/alicloud v1.212.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_ess_scaling_group

### Terraform Configuration Files
```hcl
resource "alicloud_ess_scaling_group" "worker" {
  resource_group_id  = var.resource_group_id
...
}
```

### Debug Output
Background: I'v create a new resource_group for all resources for my current proejct

When I remove or recreate relevant resources for  resources`alicloud_ess_scaling_group` got the error below

```bash
╷
│ Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_kubernetes_node_pool.go:892: Resource c932fc959edca4118b31207aba4b43282:npf4820155f79d4589ad410935ffbc42fd UpdateKubernetesNodePool Failed!!! [SDK denverdino/aliyungo ERROR]:
│ Aliyun API Error: RequestId: EE4DC79F-0F85-5C7B-A2AF-E826C2000F4A Status Code: 400 Code: ErrUpdateNodePool Message: SDK.ServerError
│ ErrorCode: InvalidScalingGroupId.NotFound
│ Recommend: https://api.aliyun.com/troubleshoot?q=InvalidScalingGroupId.NotFound&product=Ess-inner&requestId=643B7201-930D-5250-B578-0F5652FDD510
│ RequestId: 643B7201-930D-5250-B578-0F5652FDD510
│ Message: The specified scaling group does not exist.
│ RespHeaders: map[Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[*] Connection:[keep-alive] Content-Length:[334] Content-Type:[application/json;charset=utf-8] Date:[Sat, 18 Nov 2023 15:27:46 GMT] Keep-Alive:[timeout=25] X-Acs-Request-Id:[643B7201-930D-5250-B578-0F5652FDD510] X-Acs-Trace-Id:[533280759b47ba3a347bbd1ce3b444c0]]
```

When I try to remove the node pool got samilar issue, I finally find the alicloud_ess_scaling_group is located in the default resource group and when I add the resources_gruop_id to it got the error

```bash
│ An argument named "resource_group_id" is not expected here.
```

Delete on the web console, got

<img width="476" alt="Screenshot 2023-11-19 at 00 01 32" src="https://github.com/aliyun/terraform-provider-alicloud/assets/137862870/cb5c5cda-a370-45ba-8844-25e9c45764ea">

**Comment by fuliu-zln** [comment]
V1.224.0 has supported resource_group_id

**Comment by xiaozhu36** [comment]
@fuliu-zln Thanks for your feedback. @ik8svip Please refer to [resource_group_id](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/ess_scaling_group#resource_group_id).
