### ISSUE TITLE
License on transitive dependencies

### ISSUE THREAD

**Issue by iwahbe** [aliyun/terraform-provider-alicloud#6715]
Hi,

I work for Pulumi and we depend on [terraform-provider-alicloud](https://github.com/aliyun/terraform-provider-alicloud) for [pulumi-alicloud](https://github.com/pulumi/pulumi-alicloud). As part of the update to v1.213.0, terraform-provider-alicloud took a dependency on repos that don't have a license listed:

- github.com/alibabacloud-go/alibabacloud-gateway-sls-util/client
- github.com/alibabacloud-go/alibabacloud-gateway-sls/client
- github.com/alibabacloud-go/darabonba-array/client
- github.com/alibabacloud-go/darabonba-encode-util/client
- github.com/alibabacloud-go/darabonba-map/client
- github.com/alibabacloud-go/darabonba-signature-util/client

Would it be possible to add a LICENSE to these repos?

P.S. The repos mentioned have disabled issues, which is why I am opening the request here.

Thanks for your time.

**Comment by xiaozhu36** [comment]
HI @iwahbe Thanks for your feedback and patient. I noticed above repos have been added license now, and please update them.
