### ISSUE TITLE
ECI created by Auto Scaling will terminate soon after created

### ISSUE THREAD

**Issue by berryfl** [aliyun/terraform-provider-alicloud#6852]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.0.8

### Affected Resource(s)
- alicloud_ess_eci_scaling_configuration

### Terraform Configuration Files
```
resource "alicloud_ess_eci_scaling_configuration" "default" {
  scaling_configuration_name = local.name
  scaling_group_id           = alicloud_ess_scaling_group.default.id
  cpu                        = var.tls_proxy_cpu
  memory                     = var.tls_proxy_memory
  force_delete               = true
  active                     = true
  container_group_name       = local.name
  security_group_id          = alicloud_security_group.default.id
  # active_deadline_seconds    = 1000000000 # run long enough
  containers {
    name              = "envoy-tls-proxy"
    image             = var.tls_proxy_image
    image_pull_policy = "IfNotPresent"
  }
}
```

### Expected Behavior
The Container Instance should run forever in normal scenario.

### Actual Behavior
The Container Instance will stop and deleted soon after created, with the error message: "pod was active on the node longer than the specified deadline"

### Steps to Reproduce
1. `terraform apply`
2. observe Elastic Compute Instance console

I guess the terraform will call the API with `activeDeadlineSeconds` set to 0 in default case, I can set it to a large value to work around. When I Create the Auto Scale Group in UI, I don't encounter this problem.

**Comment by fuliu-zln** [comment]
In version 1.217.0 , Optimization has been done.

**Comment by xiaozhu36** [comment]
Thanks for @fuliu-zln feedback, and @berryfl please upgrade provider to 1.217.0 and try again.
