### ISSUE TITLE
k8s集群pod虚拟交换机列表最大只支持10个元素

### ISSUE THREAD

**Issue by shensl** [aliyun/terraform-provider-alicloud#6939]
version: 1.215.0
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_managed_kubernetes#pod_vswitch_ids
当pod虚拟交换机列表元素大于10时出现报错：
Error: pod_vswitch_ids: attribute supports 10 item maximum, config has 11 declared
将列表长度修改到10以下时正常运行，另外在容器服务控制台编辑terway-eniip组件时选择pod虚拟交换机数量大于10时可以正常修改，所以是否可以调大API支持的列表长度？

**Comment by sanyangji** [comment]
该限制已经移除。
参考 #7215 ，Release版本：v1.223.1
